#+TITLE: Does the leaf economic spectrum hold within plant functional types? A Bayesian multivariate trait meta-analysis
#+AUTHOR:
#+DATE:

#+OPTIONS: toc:nil
#+CSL_STYLE: ecology-letters.csl

#+LATEX_HEADER: \usepackage[left=1in,right=1in,top=1in,bottom=1in]{geometry}
#+LATEX_HEADER: \usepackage{lineno}

#+LATEX_HEADER: \usepackage[noblocks]{authblk}

#+LATEX_HEADER: \author[1,*]{Alexey N. Shiklomanov <alexey.shiklomanov@pnnl.gov>}
#+LATEX_HEADER: \affil[1]{Joint Global Change Research Institute, Pacific Northwest National Laboratory, College Park, MD}
#+LATEX_HEADER: \author[2]{Elizabeth M. Cowdery <ecowdery@bu.edu>}
#+LATEX_HEADER: \affil[2]{Department of Earth \& Environment, Boston University, Boston, MA}
#+LATEX_HEADER: \author[3]{Michael Bahn <Michael.Bahn@uibk.ac.at>}
#+LATEX_HEADER: \affil[3]{Institute of Ecology, University of Innsbruck, 6020 Innsbruck, Austria}
#+LATEX_HEADER: \author[4]{Chaeho Byun <chaeho.byun@mail.mcgill.ca>} %%% Emailed %%%
#+LATEX_HEADER: \affil[4]{School of Civil and Environmental Engineering, Yonsei University, Seoul, Korea}
#+LATEX_HEADER: \author[5]{Joseph Craine <josephmcraine@gmail.com>} %%% Emailed %%%
#+LATEX_HEADER: \affil[5]{Jonah Ventures, LLC, Manhattan, KS 66502, USA}
#+LATEX_HEADER: \author[6]{Andr\'es Gonzalez-Melo <geagonzalezme@unal.edu.co>} %%% Emailed %%%
#+LATEX_HEADER: \affil[6]{Universidad del Rosario. Facultad de Ciencias Naturales y Matematic\'as. Carrera 26 63B-48. Bogot\'a, Colombia}
#+LATEX_HEADER: \author[7]{Steven Jansen <steven.jansen@uni-ulm.de>}
#+LATEX_HEADER: \affil[7]{Institute of Systematic Botany and Ecology, Ulm University, Ulm, Germany}
#+LATEX_HEADER: \author[8]{Koen Kramer <koen.kramer@wur.nl>}
#+LATEX_HEADER: \affil[8]{Vegetation, Forest, and Landscape Ecology, Wageningen Environmental Research and Wageningen University, Wageningen, Gelderland, The Netherlands}
#+LATEX_HEADER: \author[09,10]{Vanessa Minden <vanessa.minden@uni-oldenburg.de>}
#+LATEX_HEADER: \affil[09]{Institute for Biology and Environmental Sciences, Carl von Ossietzky-University of Oldenburg, Carl von Ossietzky Str. 9-11, 26129 Oldenburg, Germany}
#+LATEX_HEADER: \affil[10]{Department of Biology, Ecology and Evolution, Vrije Universiteit Brussel, Pleinlaan 2, 1050 Brussels}
#+LATEX_HEADER: \author[11]{\"Ulo Niinemets <ylo.niinemets@emu.ee>}
#+LATEX_HEADER: \affil[11]{Institute of Agricultural and Environmental Sciences, Estonian University of Life Sciences, Kreutzwaldi 1, 51014 Tartu, Estonia}
#+LATEX_HEADER: \author[12]{Yusuke Onoda <yusuke.onoda@gmail.com>}
#+LATEX_HEADER: \affil[12]{Graduate School of Agriculture, Kyoto University, Kyoto, 605-8503, Japan}
#+LATEX_HEADER: \author[13]{Enio Egon Sosinski <sosinski@gmail.com>} %%%
#+LATEX_HEADER: \affil[13]{Embrapa Temperate Agriculture, Rodovia BR 391, Km 77, CEP 96009-972 Pelotas, RS, Brazil}
#+LATEX_HEADER: \author[14]{Nadejda A. Soudzilovskaia <n.a.soudzilovskaia@cml.leidenuniv.nl>}
#+LATEX_HEADER: \affil[14]{Conservation Biology Department, Institute of Environmental Sciences, Leiden University, Leiden, The Netherlands}
#+LATEX_HEADER: \author[2]{Michael C. Dietze <dietze@bu.edu>}

#+LATEX_HEADER: \affil[*]{Corresponding author; Phone: (301) 314-6713; Fax: (301) 314-6719; Email: alexey.shiklomanov@pnnl.gov; Mail: 5825 University Research Ct., Office 3533, College Park, MD 20740}

#+LATEX_HEADER: \renewcommand\Authfont{\footnotesize}
#+LATEX_HEADER: \renewcommand\Affilfont{\scriptsize}

\begin{footnotesize}

\noindent
\textbf{Article type:} Methods

\noindent
\textbf{Author contributions:}
ANS wrote the manuscript and implemented the analysis.
ANS and EMC designed the analysis and figures.
MCD conceived the original idea for the manuscript, guided its development, and provided financial support.
MB, SJ, KK, ÜN, and NAS provided extensive feedback on multiple drafts of the manuscript, and contributed data.
All other authors contributed data.

\noindent
\textbf{Data accessibility:}
The R code and ancillary data for running these analyses is publicly available online via the Open Science Framework at https://osf.io/w8y73/.
The TRY data request used for this analysis has been archived at http://try-db.org,
and can be retrieved by providing the TRY data request ID (\#1584).
Alternatively, the exact pre-formatted data used in this analysis are available on request to Alexey Shiklomanov (alexey.shiklomanov@pnnl.gov).

\noindent
\textbf{Running title:} Leaf economic spectrum within vs. across PFTs (45 characters)

\noindent
\textbf{Keywords:} Functional trade-off; hierarchical modeling; trait variation; ecological modeling; leaf morphology; leaf biochemistry

\end{footnotesize}

#+ATTR_LATEX: :font \footnotesize
| Section               | Word count |      |            |     |
|-----------------------+------------+------+------------+-----|
| Abstract              |        146 |      | Figures    |   6 |
| Introduction          |        988 |      | Tables     |   2 |
| Materials and methods |       2056 |      | References | ??? |
| Results               |       1094 |      |            |     |
| Discussion            |       1933 |      |            |     |
|-----------------------+------------+------+------------+-----|
| Total                 |       6217 | 5000 |            |     |
#+TBLFM: @7$2=vsum(@I..II)

\linenumbers

* Abstract
  :PROPERTIES:
  :UNNUMBERED: true
  :END:
  
We investigated whether global leaf economic relationships are also present within plant functional types (PFTs), and the extent to which this hierarchical structure can be used to constrain trait estimates.
We developed a hierarchical multivariate Bayesian model that assumes separate means and covariance structures within and across PFTs and fit this model to seven leaf traits from the TRY database related to leaf morphology, biochemistry, and photosynthetic metabolism.
Trait correlations were generally consistent in direction within and across PFTs, and consistent with predictions of the leaf economic spectrum.
However, correlation strength varied substantially across PFTs indicating that leaf economic relationships within PFTs are often confounded by the unique physiology of certain plant types or environmental conditions in certain biomes.
Leveraging covariance in multivariate models reduced uncertainties in mean trait estimates, particularly for undersampled trait-PFT combinations.
However, additional constraint from the across-PFT hierarchy was limited.

* Introduction

The use of functional groups with common characteristics has been widely applied in ecological studies cite:naeem_2003_disentangling and is essential to the structure of many ecosystem models cite:lavorel_1997_plant_functional_classifications,wullschleger_2014_plant.
However, ecologists have long recognized the importance of individual variability and stochasticity in shaping ecosystems
cite:gleason_1939_individualistic,rosindell_2011_unified,bolnick_2011_why,clark_2016_why
and the benefits of more finely-resolved representation of functional diversity are supported by an increasing body of ecological literature
cite:mayfield_2006_diversity,mcmahon_2011_improving,van_2011_going,reichstein_2014_linking,violle_2014_emergence,medlyn_2015_using,moran_2015_intraspecific.
Plant functional traits can be used to link directly measurable features of individuals to their fitness within an ecosystem as well as to whole-ecosystem function cite:violle_2007_let.
Recent syntheses of global trait databases have revealed that although the functional diversity across plant species is immense, this diversity is constrained by allometries and trade-offs between plant strategies cite:kattge_2011_try,wright_2004_worldwide,kleyer_2015_why,diaz_2015_global.
One important axis of trait covariation is the "leaf economic spectrum", which defines an ecological trade-off between productive but short-lived leaves versus less productive but recalcitrant and long-lived leaves cite:wright_2004_worldwide,shipley_2006_fundamental,reich_2014_world,diaz_2015_global. 
Leaf economic traits are well-correlated with
individual plant productivity cite:shipley_2005_functional,niinemets_2016_within,wu_2016_convergence,
litter decomposition rates cite:bakker_2010_leaf,hobbie_2015_plant,
community composition cite:burns_2004_patterns,cavender-bares_2004_multiple,
and ecosystem function cite:diaz_2004_plant,musavi_2015_imprint.
The relative position of plant species along the leaf economic spectrum has been shown to be influenced by climate and soil conditions
cite:wright_2004_worldwide,wright_2005_modulation,cornwell_2009_community,ordonez_2009_global,wigley_2016_leaf.
As a result, relationships between leaf economic traits and climate have been incorporated into ecosystem models to allow for more finely-resolved variation in plant function cite:sakschewski_2015_leaf,verheijen_2015_inclusion.

However, the use of among-trait and trait-environment correlations at the global scale, for both ecological inference and land surface modeling, has several important caveats.
First, observed correlations at the global scale may not hold at smaller scales, such as sites, species, and individuals.
Some studies suggest consistent correlations across scales cite:wright_2004_worldwide,albert_2010_multi,asner_2014_amazonian,
whereas others show no or even opposite correlations cite:albert_2010_intraspecific_functional_variability,messier_2010_how,wright_2012_does,feng_2013_scale,grubb_2015_relationships,wigley_2016_leaf,messier_2017_interspecific,kichenin_2013_contrasting.
Many mechanisms have been suggested for scale-dependence of trait relationships.
Trade-offs may only be applicable when multiple competing strategies co-occur, and where strong environmental filters severely limit the range of feasible strategies, alternative processes can drive community assembly cite:rosado_2017_relative,grime_2012_evolutionary.
Different selective pressures dominate at different scales, particularly within versus across species cite:albert_2010_intraspecific_functional_variability,messier_2010_how,kichenin_2013_contrasting,
and different traits have contrasting sensitivity to these different pressures cite:messier_2016_trait.
Experimental evidence shows that species can alter different aspects of their leaf economy more-or-less independently cite:wright_2012_does.
Meanwhile, across different plant functional types, resource allocation patterns differ substantially, which implies different investment strategies and therefore varying relationships among traits cite:ghimire_2017_global.
Second, among-trait correlations at any scale do not provide causal evidence for functional trade-offs or similarity in environmental responses cite:messier_2016_trait.
Therefore, ascribing too much leverage to trait correlations can lead to an underestimation of functional diversity cite:grubb_2015_trade.
Third, plants maintain their fitness through multiple independent strategies, corresponding to multiple mutually orthogonal axes of trait variability.
For instance, changes in leaf economic traits, such as nitrogen content and specific leaf area, can fail to predict changes in other aspects of plant function, such as
hydraulics cite:li_2015_leaf,
dispersal cite:westoby_2002_plant_ecological_strategies,
and overall plant carbon budget cite:edwards_2014_leaf.
Finally, modeling ecosystem function based on trait correlations is sampling from the hypothetical space of potential species and communities that could have evolved,
failing to account for the timescales required for adaptation and community assembly, physiological limitations of different species, spatial separation, and constraints on convergent evolution.

An alternative approach is to preserve existing PFT classifications
(though potentially with finer taxonomic, functional, or spatial resolution, e.g. cite:boulangeat_2012_improving)
while using statistical analyses to account for uncertainty and variability in the aggregated trait values.
For example, the Predictive Ecosystem Analyzer (PEcAn, pecanproject.org), an ecosystem model-data informatics system, parameterizes PFTs using trait probability distributions from a Bayesian meta-analysis of plant trait data across many studies
cite:dietze_2013_improving,lebauer_2013_facilitating. 
This approach explicitly separates the processes driving PFT-level differentiation from processes that drive finer-scale functional variability,
and is useful for guiding future data collection and model refinement cite:dietze_2014_quantitative.
However, a univariate meta-analysis, like the one currently in PEcAn, fails to account for trait correlations and therefore neglects useful knowledge about relationships across PFTs and between traits.
At the other extreme, existing regional and global scale analyses (e.g. cite:van_2011_going,sakschewski_2015_leaf) ignore variability within PFTs, often resulting in macroecological, evolutionary, and competitive trade-offs across PFTs being used to drive both acclimation and instantaneous responses within PFTs.

While the leaf economic spectrum has been investigated at the global scale, where it is robust, and at the site or plot scale, where deviations from it are common, it has received less attention at the intermediate scale of PFTs.
Thus, this paper seeks to answer the following questions:
First, to what extent does the leaf economic spectrum hold within vs. across PFTs?
Second, to what extent can the leaf economic spectrum and other patterns of trait covariance be leveraged to constrain trait estimates, particularly under data limitation?
The answer to these question has implications for both functional ecology and ecosystem modeling.
To evaluate these questions, we develop a hierarchical multivariate Bayesian model that explicitly accounts for across- and within-PFT variability in trait correlations.
We then fit this model to a global database of foliar traits to estimate mean trait values and variance-covariance matrices for PFTs as defined in a major earth system model (Community Land Model, CLM, citealt:clm45_note).
We evaluate the ability of this model to reduce uncertainties in trait estimates and reproduce observed patterns of global trait variation compared to non-hierarchical multivariate and univariate models.
Finally, we assess the generality and scale dependence of trait trade-offs by comparing covariance estimates globally and within each PFT.

* Materials and methods

** Trait data

   # TODO - Table reference
Foliar trait data for this analysis comes from the TRY global traits database cite:kattge_2011_try (Tab.\ =\@ref(tab:trydata)=).
We focused on seven foliar traits:
Leaf longevity (months),
specific leaf area (SLA, m$^2$ kg$^{-1}$),
leaf nitrogen content ($N_{mass}$, mg N g$^{-1}$ or $N_{area}$, g m$^{-2}$),
leaf phosphorus content ($P_{mass}$, mg P g$^{-1}$ or $P_{area}$, g m$^{-2}$),
leaf dark respiration at 25°C ($R_{d,mass}$, µmol g$^{-1}$ s$^{-1}$, or $R_{d,area}$, µmol m$^{-2}$ s$^{-1}$),
maximum Rubisco carboxylation rate at 25°C ($V_{c,max,mass}$, µmol g$^{-1}$ s$^{-1}$, or $V_{c,max,area}$, µmol m$^{-2}$ s$^{-1}$),
and maximum electron transport rate at 25°C ($J_{max,mass}$, µmol g$^{-1}$ s$^{-1}$, or $J_{max,area}$, µmol m$^{-2}$ s$^{-1}$).
For $V_{c,max}$, we only used values already reported in TRY as being at 25°C.
For $R_{d}$, we normalized the values to 25°C based on reported leaf temperature values following the same methods as citet:atkin_2015_global.
For $J_{max}$, we normalized the values to 25°C based on reported leaf temperature values using the temperature response function described in citet:kattge_2007_temperature (Equation 1 therein).
To avoid potential artifacts caused by different trait normalization, we performed analyses separately for both mass- and area-normalized traits cite:osnas_2013_global,lloyd_2013_photosynthetically.
We restricted our analysis to TRY data that have been quality-controlled, where at least one of the above traits was observed, and for which adequate species information was provided for functional type classification [[cite:kattge_2011_try][see]].

Although the maximum photosynthetic rate ($A_{max}$) was an important trait in previous studies, we did not include it for two reasons.
First, data on raw photosynthetic rates are highly sensitive to measurement methodology and environmental conditions, which were generally inconsistent or unavailable in TRY.
Second, $A_{max}$ is rarely used in vegetation models as a photosynthetic parameter because it integrates over variability in many physiologically independent traits, such as $V_{c,max}$, $J_{max}$, and stomatal conductance cite:ali_2015_global.

Following past studies [[cite:wright_2004_worldwide,onoda_2011_global,diaz_2015_global][e.g.]], we log-transformed all trait values to correct for their strong right-skewness.

** Plant functional types

   # TODO - Table reference
We assigned each species a unique plant functional type (PFT) following the scheme in the Community Land Model (CLM4.5, citealt:clm45_note) [Tab.\ \@ref(tab:pfts), Fig.\ 1].
We obtained categorical data on growth form, leaf type, phenology, and photosynthetic pathway from the TRY database.
Where species attributes disagreed between datasets, we assigned the most frequently observed attribute (e.g., if five datasets say "shrub" but only one says "tree", we would use "shrub").
Where species attributes were missing entirely, we assigned attributes based on higher order phylogeny if this was reasonably unambiguous (e.g., /Poaceae/ family are grasses, /Larix/ genus are deciduous needleleaved trees) and omitted the species if otherwise.
For biome specification, we collected all latitude and longitude data for each species,
matched these data to mean annual temperature ($AMT$, averaged 1970-2000) data from WorldClim-2 cite:fick_2017_worldclim,
calculated the mean AMT for all sites at which that species was observed,
and then binned these species based on the following cutoffs: boreal/arctic ($AMT \leq 5^\circ C$), temperate ($AMT \leq 20^\circ C$), and tropical ($AMT > 20^\circ C$).

** Multivariate analysis

*** Basic model description

In this study, we compared three models representing different levels of complexity.

The simplest model was the "univariate" model, in which each trait is independent.
For an observation $x_{i,t}$ of trait $t$ and sample $i$:

$$x_{i,t} \sim N(\mu_t, \sigma_t)$$

where $N$ is the univariate Gaussian distribution with mean $\mu_t$ and standard deviation $\sigma_t$ for trait $t$.

The second-simplest model was the "multivariate" model, in which traits are drawn from a single, common multivariate distribution.
For observed trait vector ${\mathbf{x_i}}$ for sample $i$:

$$\mathbf{x_i} \sim mvN(\mathbf{\mu}, \mathbf{\Sigma})$$

where $mvN$ is the multivariate Gaussian distribution with mean vector $\mathbf{\mu}$ and variance-covariance matrix $\mathbf{\Sigma}$.
We ran both of these models independently for each PFT and once for the entire dataset (i.e. one global PFT).

The most complex model was the "hierarchical" model, where traits are drawn from a PFT-specific multivariate distribution describing within-PFT variation, and whose parameters in turn are sampled from a global multivariate distribution describing variation across PFTs.
For observed trait vector $\mathbf{x}_{i,p}$ for sample $i$ belonging to PFT $p$:

$$\mathbf{x}_{i,p} \sim mvN(\mathbf{\mu}_p, \mathbf{\Sigma}_p)$$
$$\mathbf{\mu}_p \sim mvN(\mathbf{\mu}_g, \mathbf{\Sigma}_g)$$

where $\mathbf{\mu}_p$ and $\mathbf{\Sigma}_p$ are the mean vector and variance-covariance matrix describing variation within PFT $p$, and $\mathbf{\mu}_g$ and $\mathbf{\Sigma}_g$ are the mean vector and variance-covariance matrix describing across-PFT (global) variation.


*** Model implementation

We fit the above models using a Gibbs sampling algorithm that leveraged known conjugate prior relationships for efficient exploration of the sampling space.
For priors on all multivariate mean vectors ($\mathbf{\mu}$), we use normal distributions:

$$P(\mathbf{\mu}) \sim mvN(\mathbf{\mu}_0, {\mathbf{\Sigma}}_0)$$

This gives rise to the following expression for the posterior:

$$P(\mathbf{\mu} \mid 
    \mathbf{x}, \mathbf{\Sigma}, 
    \mathbf{\mu}_0, \mathbf{\Sigma}_0)
  \sim
  mvN(\mathbf{\mu^*}, \mathbf{\Sigma^*})$$

$$\mathbf{\Sigma^*} = (\mathbf{\Sigma}_0^{-1} + n \mathbf{\Sigma}^{-1})^{-1}$$
$$\mathbf{\mu^*} = \mathbf{\mu}_0 \mathbf{\Sigma}_0^{-1} + \bar{\mathbf{x}} n \mathbf{\Sigma}^{-1}$$

where ${\bar{{\mathbf{x}}}}$ are the sample means of the data and $n$ is the number of rows in the data.

For priors on all multivariate variance-covariance matrices, we used the Wishart distribution ($W$):

$$P(\mathbf{\Sigma}) \sim W(\nu_0, \mathbf{S}_0)$$

This gives rise to the following expression for the posterior:

$$P(\mathbf{\Sigma} \mid
  \mathbf{x}, \mathbf{\mu},
  \nu_0, \mathbf{\Sigma}_0)
\sim
  (W(\nu^*, S^*))^{-1}$$

$$\nu^* = 1 + \nu_0 + n + m$$
$$\mathbf{x^*} = \mathbf{x} - \bar{\mu}$$
$$\mathbf{SS} = \mathbf{x^*}^{T} \mathbf{x^*}$$
$$\mathbf{S^*} = (\mathbf{S}_0 + \mathbf{SS})^{-1}$$

where $n$ is the number of rows and $m$ is the number of columns in data matrix $x$. For further details on this derivation, see citet:gelman_2003_bayesian.

The multivariate nature of the sampling procedure described above makes it incapable of accommodating partially missing observations.
Therefore, our algorithm included multiple imputation of partially missing data, which proceeded as follows:
For a block of data $\mathbf{x\prime}$ containing missing observations in columns $\mathbf{m}$ and present observations in columns $\mathbf{p}$,
missing values $\mathbf{x\prime}[m]$ are drawn randomly from a conditional multivariate normal distribution at each iteration of the sampling algorithm:

$$\mathbf{x^\prime}[m|p] \sim mvN(\mathbf{\mu}^\prime, \mathbf{\Sigma}^\prime)$$

$$\mathbf{\mu\prime} = 
  (\mathbf{x\prime}[p] - \mathbf{\mu^\prime}[p]) 
  (\mathbf{\Sigma}[p,p]^{-1} \mathbf{\Sigma}[p,m])$$
$$\mathbf{\Sigma\prime} = \mathbf{\Sigma}[m,m] - 
  \mathbf{\Sigma}[m,p]
  (\mathbf{\Sigma}[p,p]^{-1} \mathbf{\Sigma}[p,m])$$
  
We emphasize that imputation of missing data is performed iteratively as parameters are being estimated, such that each set of imputed values is conditioned on the current sampled state of the parameters.
This approach is distinct from single imputation, where data are imputed first in a separate step prior to parameter estimation cite:white_2010_multiple,graham_2009_missing_data_analysis.
A demonstration of this multiple imputation approach and how it is used to estimate trait covariance is provided Supporting Information Method S1.

For each model fit, we ran five parallel MCMC chains, continuing the sampling until the final result achieved convergence as determined by a Gelman-Rubin potential scale reduction statistic less than 1.1 cite:gelman_1992_inference.
We implemented this sampling algorithm in an open source, publicly available R cite:team_2018_r package (<http://github.com/ashiklom/mvtraits>).


*** Analysis of results

To assess the impact of multivariate and hierarchical constraint on trait estimates,
we compared the mean and 95% confidence intervals of trait estimates for each PFT from each model (Fig.\ 2, Tab.\ S1 and S2).
For reference, we also added the default parameter values of CLM 4.5 [[cite:clm45_note][Table 8.1 in]] for SLA, $N_{mass}$, $N_{area}$, $V_{c,max,mass}$, and $V_{c,max,area}$ to Fig.\ 2.
To convert CLM's reported C:N ratio to $N_{mass}$, we assumed a uniform leaf C fraction of 0.46.
We then divided this calculated $N_{mass}$ by the reported SLA to obtain $N_{area}$.
We calculated $V_{c,max,mass}$ by multiplying the reported $V_{c,max,area}$ by the reported SLA.

To test whether the multivariate and hierarchical models offer more value in terms of uncertainty constraint at smaller sample sizes, we calculated the relative uncertainty ($\alpha$) as a function of the mean ($\mu$) and upper ($q_{0.975}$) and lower ($q_{0.025}$) confidence limits of trait estimates.

$$ \alpha = \frac{q_{0.975} - q_{0.025}}{\mu} $$

We then fit a log-linear least-squares regression relating relative uncertainty to sample size ($n$) for each model (univariate, multivariate, and hierarchical; Fig. 3).

$$ \log{\alpha} = b_0 + b_1 \log{n} $$

If all three models performed equally well at all sample sizes, their respective slope and intercept coefficients would be statistically indistinguishable.
On the other hand, models that perform better should have
lower intercept ($b_0$) coefficients, indicating lower overall uncertainty,
and
lower slope ($b_1$) coefficients, indicating a reduced sensitivity of uncertainty ($\alpha$) to sample size ($n$).

To assess the consistency of within- and across-PFT trait trade-offs, we looked at covariance estimates for each trait pair and, where these values were significantly different from zero ($p < 0.05$),
we calculated the eigenvalues from the variance-covariance matrix for just that trait pair and plotted the corresponding dominant eigenvectors centered on the mean estimates (Fig.\ 4).
This figure provides a visual representation of relative positions of PFTs in trait space and both the direction and extent of within-PFT trait covariance.
It is analogous to conceptual figures describing hierarchical trait variability across environmental gradients as presented in citet:cornwell_2009_community and citet:albert_2010_intraspecific_functional_variability.
Due to the small number of points used to estimate across-PFT covariance in the hierarchical model, none of the across-PFT covariances estimated in the hierarchical model were significantly different from zero ($p < 0.05$).
Therefore, we compared within-PFT covariances as estimated by the hierarchical model against covariances estimated by a single global multivariate model.

Besides the consistency in the direction of trait covariance within vs. across PFTs, we also investigated the strength and predictive power of these covariances, represented by correlation coefficients (i.e. pairwise covariance normalized by each trait's variance).
We plotted the mean and 95% confidence interval of the pairwise trait correlation coefficients from the global multivariate model and PFT-specific estimates from the hierarchical model (Fig.\ 5).

Correlation coefficients can be strongly influenced by data sampling, particularly sample size and range (correlations are typically stronger when data have more samples and a larger range).
To evaluate the contribution of data sampling to our correlation predictions, we plotted the square of each pairwise correlation coefficient against pairwise sample size and normalized data range (Fig.\ S1 and S2).

The R code and ancillary data for running these analyses is publicly available online via the Open Science Framework at https://osf.io/w8y73/.
The TRY data request used for this analysis has been archived at http://try-db.org,
and can be retrieved by providing the TRY data request ID (#1584).
Alternatively, the exact pre-formatted data used in this analysis are available on request to Alexey Shiklomanov (alexey.shiklomanov@pnnl.gov).

* Results

** Estimates of PFT-level means

In general, leaf trait estimates from the univariate, multivariate, and hierarchical models were similar (Fig.\ 2, Tab.\ S1 and S2).
Where estimates differed between models, the largest differences were between the univariate and multivariate models, and additional constraint from the hierarchical model relative to PFT-specific multivariate models had a minimal effect on trait estimates.
Significant differences in trait estimates between univariate and multivariate models occurred even for well-sampled traits, such as leaf nitrogen content.

Evergreen PFTs, particularly temperate and boreal needleleaf trees, had the longest leaf lifespan.
Meanwhile, all deciduous PFTs had lifespans shorter than 7 months, with generally longer lifespan in warmer biomes than colder ones.

Across-PFT patterns in SLA and $N_{mass}$, $P_{mass}$, and $R_{d,mass}$ were similar,
with the highest values in temperate broadleaved deciduous PFTs and the lowest values in temperate evergreen PFTs.
However, none of these patterns was universal to all four traits.
For example, tropical evergreen trees had relatively high $N_{mass}$ and average SLA and $R_{d,mass}$, but among the lowest $P_{mass}$.
Similarly, compared to grass PFTs, temperate and boreal shrubs had similar SLA but higher $N_{mass}$ and $P_{mass}$. 
Patterns were different when these traits were normalized by area instead of mass.
For example, tropical broadleaved evergreen and needleleaf evergreen trees had relatively low $N_{mass}$ and $P_{mass}$ but relatively high $N_{area}$ and $P_{area}$, while the opposite was true of deciduous temperate trees and shrubs.

C3 grasses had the highest $V_{c,max,mass}$ and $V_{c,max,area}$.
Compared to broadleaved trees, temperate needleleaved evergreen trees had lower $V_{c,max,mass}$ but higher $V_{c,max,area}$.
Among broadleaved trees, deciduous trees had higher $V_{c,max,mass}$ and slightly higher $V_{c,max,area}$ than evergreen trees.
Between the deciduous and evergreen tree PFTs, we observed no significant trend by climate zone.

C3 grasses and temperate needleleaved evergreen trees had the highest $J_{max,area}$, but temperate broadleaved deciduous trees had the highest $J_{max,mass}$.
All of the shrub PFTs had the lowest $J_{max,mass}$ but average or above-average $J_{max,area}$, while the opposite was true of broadleaved tropical PFTs.
Of the tree PFTs, needleleaved evergreen trees had the highest $J_{max,area}$ but the lowest $J_{max,mass}$.

A key application of this study was to provide data-driven parameter estimates for Earth System Models.
To this end, we compared our mean parameter estimates with corresponding default parameters in CLM 4.5 cite:clm45_note (Fig.\ 2).
Our SLA estimates were significantly lower than CLM parameters for all PFTs except tropical broadleaved evergreen trees.
For $N_{mass}$, our estimates showed a lot more across-PFT variability than CLM parameters, and only agreed with CLM parameters for evergreen temperate trees, needleleaved trees, and C3 arctic grasses.
Our estimates of $V_{c,max}$ (both by mass and area) were generally lower than CLM's parameters.
citet:kattge_2009_quantifying also found that $V_{c,max,area}$ was overestimated by Earth System models,
but their estimates of $V_{c,max,area}$ and $N_{area}$ are generally slightly higher than ours.

We observed clear differences in the relative uncertainties of mean estimates with respect to sample size.
All high-latitude PFTs consistently had large uncertainties relative to other PFTs, while the traits with the largest uncertainties were dark respiration, $V_{c,max}$, and $J_{max}$.
For many of these trait-PFT combinations, the additional constraint from trait covariance provided by the multivariate and hierarchical models substantially reduced error bars, making it possible to compare estimates against those of other PFTs.
Our analysis of the relationship between sample size and trait uncertainty found that covariance-based constraint from the multivariate model both reduced uncertainty overall (lower intercept) and reduced the sensitivity of uncertainty to sample size (lower slope) compared to the univariate model (Fig.\ 3).
However, the additional benefit from the hierarchical model was small.


** Trait correlation patterns across- and within-PFTs

For all traits except leaf lifespan, pairwise trait correlations were generally consistent in direction both globally and within each PFT (Fig.\ 4).
Mass- and area-normalized traits were all positively correlated with each other and, respectively, positively and negatively correlated with SLA, both globally and within each PFT.
Mass-based traits were also generally positively correlated with leaf lifespan, but correlations of area-based traits with leaf lifespan were more variable.
The correlation between $N_{area}$ and leaf lifespan was positive globally and for evergreen shrubs, tropical broadleaved deciduous trees, temperate needleleaved evergreen trees but negative for temperate and boreal broadleaved deciduous trees and not significant for any other PFTs.
Similarly, the correlation between $P_{area}$ and leaf lifespan was positive globally but negative for evergreen shrubs and not significant for any other PFTs.
The correlation between leaf lifespan and $R_{d,area}$ was significant and negative globally, but was not significant within any PFTs.
The only significant correlations of leaf lifespan with $V_{c,max,area}$ and $J_{max,area}$ were negative for temperate broadleaved deciduous trees.

Pairwise trait correlation strength varied depending on scale, PFT, and trait (Fig.\ 5).
In some cases, this variability was driven by low sample sizes (Fig.\ 1, S1; Tab.\ S3, S4).
For instance, needleleaved deciduous trees, the most undersampled PFT in our analysis, were often the only PFT for which a correlation was not statistically significant.
Similarly, we had no observations of dark respirations for deciduous boreal shrubs, which explains why we found no significant correlations of dark respiration with any other trait for that PFT.
That being said, the relationship between correlations strength and sample size was inconsistent (Fig.\ S1; Tab.\ S4).
For example, temperate needleleaf evergreen trees and C3 arctic grasses showed the strongest $N_{area}$-$P_{area}$ correlations despite having relatively average sample sizes for both traits.
In fact, every trait pair had at least one case (and often several cases) where a better-sampled PFT showed weaker correlations than PFTs with lower sample sizes, or where correlation strength varied significantly among PFTs with similar sample sizes (Fig.\ S1).
Relationships between correlation strength and data range were even less consistent (Fig.\ S2).
Based on these results, we conclude that the variation in our correlation results is not driven primarily by sampling and at least partially captures underlying ecophysiological differences between PFTs.

* Discussion

** Scale dependence of the leaf economic spectrum

The canonical leaf economic spectrum is defined by a negative correlation of between SLA and leaf lifespan, and a positive correlation of SLA with $N_{mass}$, $P_{mass}$, and photosynthesis and respiration rates cite:wright_2004_worldwide.
The first objective of this paper was to investigate the extent to which these relationships hold within and across PFTs.
Our results indicate that the leaf economic spectrum generally still holds within PFTs, at least at the functional and phylogenetic scale of the current generation of Earth System Models.
Within PFTs, correlations between SLA, $N_{mass}$, and $P_{mass}$ were consistently positive, and correlations of these traits with leaf lifespan were generally negative (though, for many PFTs, correlations were not significantly different from zero).
Although we did not include maximum photosynthesis rate ($A_{max}$), $V_{c,max,mass}$ and $J_{max,mass}$ generally exhibited the expected positive correlations with SLA and negative correlations with leaf lifespan, as did $R_{d,mass}$, though many correlations were not significant, primarily due to sample size.

While the direction of relationships we observed was largely consistent across different PFTs, the strength of these correlations was more variable.
For example, the correlations of SLA with $N_{mass}$ and $P_{mass}$ were generally weaker in needleleaved PFTs than in broadleaved PFTs.
On the other hand, relationships of SLA and $N_{area}$ were strongly negative for all PFTs (except the data-limited needleleaved deciduous trees), and temperate needleleaved species in particular had among the strongest SLA-$N_{area}$ and SLA-$P_{area}$ correlations of any PFT.
Taken together with the finding that evergreen conifers are relatively unique in their consistently proportional allocation of N to cell walls and Rubisco cite:onoda_2017_physiological, our results support the idea that needleleaved species primarily adapt to environmental changes through structural changes (i.e. increasing or decreasing SLA) rather than through modulating foliar biochemistry cite:robakowski_2004_growth.

We also found that the strength of correlations between leaf nutrient concentrations and traits related to photosynthetic metabolism ($V_{c,max}$ and $J_{max}$)---which are often used in ecosystem modeling to parameterize photosynthesis cite:clm45_note,rogers_2016_roadmap ---were highly variable between PFTs.
Although trait correlations are not necessarily indicative of allocation strategies, this result generally supports the findings of @ghimire_2017_Nallocation that N allocation strategies to photosynthesis vary widely by plant functional type.
In particular, the correlations of $N_{mass}$ with traits related to photosynthesis and respiration ($R_{d,mass}$, $V_{c,max,mass}$, and $J_{max,mass}$) were weaker for tropical evergreen broadleaved trees than for most other PFTs, but the correlation of these traits with $P_{mass}$ was comparable or even slightly higher.
This suggests that the productivity of tropical species is generally P-limited cite:reich_2004_global,ghimire_2017_global, that N allocation strategies are more variable under N-poor than N-rich conditions cite:ghimire_2017_global, or more generally that photosynthetic parameters are affected more strongly by environmental covariates than leaf nitrogen contents cite:ali_2015_global.
Meanwhile, our result that the $N_{area}$ - $V_{c,max,area}$ correlation is generally weaker for needleleaved than broadleaved species was also found by @kattge_2009_vcmax, and supports the lower allocation of N to photosynthesis found by citet:ghimire_2017_global.
In light of this fact and considering that boreal forests, largely populated by needleleaf species, have the largest influence on global climate of any biome cite:snyder_2004_evaluating,bonan_2008_forests_climate_change, we suggest that parameterization of needleleaf tree productivity based on foliar nitrogen content in Earth System Models be treated with caution.

Correlations of all traits with leaf lifespan were weaker (often to the point of becoming insignificant) within most PFTs than globally.
This suggests that leaf economic relationships related to leaf lifespan are dominated by the fundamental differences between deciduous and evergreen PFTs, while the factors driving variability in leaf lifespan within PFTs are more complex and idiosyncratic cite:reich_2014_biogeographic,wu_2016_leaf.
That being said, much of this within-PFT variability is known to be driven by variations in shade responses, and a key limitation of our study is that we have no information about the relative canopy positions at which traits were collected cite:lusk_2008_why,keenan_2016_global.

Across PFTs, the interaction between growth form and biome in PFT definitions (Table 1) confounds the interpretation of our results with respect to well established ecological and biogeographic patterns.
For example, citet:poorter_2009_causes found variation in SLA by growth form was, from highest to lowest, grasses, deciduous woody plants, evergreen woody plants, and succulents, while the pattern by biome was, again from highest to lowest, grassland, tundra, tropical forest, temperate forest, woodland, shrubland, and desert.
We observed as expected that arctic grasses had lower mean SLA than temperate grasses, and that evergreen trees had lower SLA than their deciduous counterparts.
However, we observed by far the highest mean SLA values in temperate deciduous broadleaf trees, rather than in grass PFTs as expected.
Similarly to citet:onoda_2011_global, we found no consistent patterns in SLA with temperature:
Among broadleaved evergreen PFTs, temperate species had lower SLA than tropical, but among broadleaved deciduous PFTs, temperate species had higher SLA than both tropical and boreal species.
With respect to the expected decline in foliar N:P ratios with latitude cite:reich_2004_global, we found that $N_{mass}$ was generally higher in PFTs associated with colder biomes compared to warmer ones, but observed biome-related differences in $P_{mass}$ only among deciduous broadleaved and needleleaved evergreen PFTs.
Contrary to citet:atkin_2015_global, our results for both $R_{d,mass}$ and $R_{d,area}$ failed to show a trend with respect to biome.
However, this comparison may not be entirely fair because our study design inherently averages over the extensive climatic variability within PFTs.

Finally, there has been some debate in the trait ecology community about the use of mass- or area-normalized traits in analyses of the leaf economic spectrum.
Two studies cite:osnas_2013_global,lloyd_2013_photosynthetically independently concluded that leaf economic relationships among mass-based traits emerge inevitably out of variation in SLA and are therefore not ecologically meaningful.
Responses to these criticisms have suggested that both mass- and area-based normalization have merit, as mass-based traits have a natural interpretation in terms of investment costs and allocation while area-based traits are important due to the fundamentally area-based nature of energy and gas fluxes through leaf surfaces cite:westoby_2013_understanding,poorter_2013_trait_correlation_networks.
Our study suggests the latter, that investigation of trait correlations on both a mass- and area-basis can yield biologically and ecologically meaningful conclusions.
For one, our discussion of differences in ecological strategies between broadleaved and needleaved species fundamentally depends on comparative analysis of mass- and area-normalized nutrient contents.
Meanwhile, our discussion of tropical tree productivity with respect to foliar nutrient contents is generally supported by both mass- and area-normalized traits (i.e. the correlation between $P$ and $V_{c,max}$ is stronger than the correlation of $N$ and $V_{c,max}$ for tropical species whether we use the mass- or area-normalized versions of these traits).


** Covariance as constraint

The second objective of this paper was to investigate the ability of trait covariance to provide additional information that could be used to reduce uncertainties in trait estimates.
In agreement with our expectations, our results show that accounting for trait covariance constrained the uncertainty around PFT-level trait means, particularly for trait-PFT combinations with low sample sizes (Fig.\ 2 and 3).
Moreover, accounting for trait covariance occasionally also changed the position of trait mean estimates, even for PFT-trait combinations with relatively large sample sizes (e.g. $N_{mass}$ for temperate broadleaved deciduous trees, Fig.\ 2).
This result echoes citet:diaz_2015_global in demonstrating the importance of studying the multivariate trait space rather than individual traits. 
Such shifts suggest that the sampling of these traits in the TRY database is not representative, which is evident from looking at the relative sample sizes of different traits (Fig.\ 1; see also citealt:kattge_2011_try). 
These shifts also indicate that parameter estimates based on univariate trait data [[cite:lebauer_2013_facilitating,dietze_2014_quantitative,butler_2017_mapping][e.g.]] may not only be overestimating uncertainty, but may also be systematically biased.
Although our results clearly show that many time- and labor-intensive traits, such as $R_{d}$, $V_{c,max}$, and $J_{max}$, still lack the observations to estimate covariance with other traits for certain PFTs,
our results also show that the effective sample size of all traits is enhanced when covariance is taken into account.
For example, field and remote sensing studies that estimate only certain traits like SLA and $N_{mass}$ but not others (such as $P_{mass}$ and $R_{d,mass}$) can leverage trait correlations to provide indirect constraint cite:singh_2015_imaging,musavi_2015_imprint,lepine_2016_examining,serbin_2014_spectroscopic.
We therefore suggest that future observational campaigns consider trait covariance when deciding which traits to measure.

The additional benefit of hierarchical multivariate modeling in our study was limited, largely due to the relatively low number of points used to estimate that across-PFT covariance structure.
Therefore, for parameterizing the current generation of ecosystem models using well-sampled traits, we suggest that simple multivariate models fit independently to each PFT are sufficient and that the additional conceptual challenges and computational overhead of hierarchical modeling are not required.
However, for modeling work that requires larger numbers of PFTs cite:boulangeat_2012_improving, and especially for models that are parameterized on the basis of individual species [[cite:post_1996_linkages][e.g. Linkages, ]], the benefits of hierarchical modeling may accumulate cite:dietze_2008_capturing,cressie_2009_accounting,webb_2010_structured,clark_2004_why.

More generally, we foresee tremendous potential of multivariate and hierarchical modeling approaches to elucidating the role of functional traits in organismal and ecosystem function. 
Besides the many important foliar traits that we did not include (e.g.\ pigment contents, leaf hydraulic traits), our approach could readily be applied to other plant traits whose relationship to the leaf economic spectrum is less clear. 
One example is hydraulic traits:
While stem and leaf hydraulic traits are correlated cite:bartlett_2016_correlations, a potential scaling between hydraulic and leaf economic traits is poorly understood cite:reich_2014_world,li_2015_leaf. 
Similarly, reexamining the relationships defining wood cite:chave_2009_towards,fortunel_2012_leaf,baraloto_2010_decoupled and root cite:kramer-walter_2016_root,valverde-barrantes_2016_root economic spectra, as well as their relationship to the foliar traits, would provide useful information on possible scale-dependence of plant growth and allocation strategies.
We emphasize that the relative difficulty of measuring hydraulic and other non-foliar traits [[cite:jansen_2015_current][e.g.]] further increases the value of any technique that can fully leverage the information they provide. 
More generally, multivariate and hierarchical modeling has the potential to reveal functional trade-offs that are mutually confounding at different scales, thereby enhancing our understanding of processes driving functional diversity.

** Conclusions

The tremendous functional diversity of plants continues to be a major challenge for functional ecology and ecosystem modeling.
Functional diversity research fundamentally depends on dimensionality reduction through a search for meaningful pattern that can be exploited to take reasonable guesses at average behavior. 
The trait trade-offs comprising the leaf economic spectrum are one such pattern. 
In this paper, we reaffirm the existence of the leaf economic spectrum both globally and, with some caveats, within plant functional types typically used in the current generation of Earth System Models.
We also highlight how the strength of leaf economic relationships can be influenced by biotic and abiotic factors specific to certain PFTs.
Finally, we show how patterns of trait covariance like the leaf economic spectrum can be leveraged to inform trait estimates, particularly at small sample sizes.

* COMMENT Local variables and settings
  
Missing references:
- Adriaenssens S. 2012. Dry deposition and canopy exchange for temperate tree species under high nitrogen deposition.
- Araujo A de, Ometto JPHB, Dolman AJ, Kruijt B, Waterloo MJ, Ehleringer JR. 2011. LBA-eco cd-02 c and n isotopes in leaves and atmospheric co2, amazonas, brazil.
- Hickler T. 1999. Plant functional types and community characteristics along environmental gradients on oland’s great alvar (sweden)
- Schweingruber F, Landolt W. 2005. The xylem database
- Vergutz L, Manzoni S, Porporato A, Novais R, Jackson R. 2012. A global database of carbon and nutrient concentrations of green and senesced leaves
- Vile D. 2005. Significations fonctionnelle et ecologique des traits de s especes vegetales: Exemple dans une succession post-cultural mediterraneenne et generalisations.
- Williams M, Shimabokuro Y, Rastetter E. 2012. LBA-ECO CD-09 soil and vegetation characteristics, tapajos national forest, brazil.
  
#+STARTUP: showall
#+STARTUP: noindent

#+BEGIN_SRC emacs-lisp :result no :eval no
(setq org-latex-pdf-process (list "latexmk -shell-escape -bibtex -f -pdf %f"))
(setq citeproc-org-ignore-backends nil)
#+END_SRC
