#+TITLE: Does the leaf economic spectrum hold within plant functional types? A Bayesian multivariate trait meta-analysis
#+AUTHOR:
#+DATE:

#+OPTIONS: toc:nil tags:nil
#+CSL_STYLE: ecology.csl

#+LATEX_HEADER: \usepackage[left=1in,right=1in,top=1in,bottom=1in]{geometry}
#+LATEX_HEADER: \usepackage{lineno}

#+LATEX_HEADER: \usepackage[noblocks]{authblk}

#+LATEX_HEADER: \usepackage{setspace}

#+LATEX_HEADER: \usepackage{booktabs}

#+LATEX_HEADER: \hypersetup{colorlinks=false, pdfborder={0 0 0}}

#+LATEX_HEADER: \author[1,*]{Alexey N. Shiklomanov <alexey.shiklomanov@pnnl.gov>}
#+LATEX_HEADER: \affil[1]{Joint Global Change Research Institute, Pacific Northwest National Laboratory, College Park, MD}

#+LATEX_HEADER: \author[2]{Elizabeth M. Cowdery <ecowdery@bu.edu>}
#+LATEX_HEADER: \affil[2]{Department of Earth \& Environment, Boston University, Boston, MA}

#+LATEX_HEADER: \author[3]{Michael Bahn <Michael.Bahn@uibk.ac.at>}
#+LATEX_HEADER: \affil[3]{Institute of Ecology, University of Innsbruck, 6020 Innsbruck, Austria}

#+LATEX_HEADER: \author[4]{Chaeho Byun <chaeho.byun@mail.mcgill.ca>}
#+LATEX_HEADER: \affil[4]{School of Civil and Environmental Engineering, Yonsei University, Seoul 03722, Korea}

#+LATEX_HEADER: \author[5]{Steven Jansen <steven.jansen@uni-ulm.de>}
#+LATEX_HEADER: \affil[5]{Institute of Systematic Botany and Ecology, Ulm University, Albert-Einstein-Allee 11, 89081, Ulm, Germany}

#+LATEX_HEADER: \author[6]{Koen Kramer <koen.kramer@wur.nl>}
#+LATEX_HEADER: \affil[6]{Department of Vegetation, Forest, and Landscape Ecology, Wageningen Environmental Research and Wageningen University, Wageningen, Gelderland, The Netherlands}

#+LATEX_HEADER: \author[7,8]{Vanessa Minden <vanessa.minden@uni-oldenburg.de>}
#+LATEX_HEADER: \affil[7]{Institute for Biology and Environmental Sciences, Carl von Ossietzky-University of Oldenburg, Carl von Ossietzky Str. 9-11, 26129 Oldenburg, Germany}
#+LATEX_HEADER: \affil[8]{Department of Biology, Ecology and Evolution, Vrije Universiteit Brussel, Pleinlaan 2, 1050 Brussels}

#+LATEX_HEADER: \author[9]{\"Ulo Niinemets <ylo.niinemets@emu.ee>}
#+LATEX_HEADER: \affil[9]{Institute of Agricultural and Environmental Sciences, Estonian University of Life Sciences, Kreutzwaldi 1, 51014 Tartu, Estonia}

#+LATEX_HEADER: \author[10]{Yusuke Onoda <yusuke.onoda@gmail.com>}
#+LATEX_HEADER: \affil[10]{Graduate School of Agriculture, Kyoto University, Kyoto, 605-8503, Japan}

#+LATEX_HEADER: \author[11]{Nadejda A. Soudzilovskaia <n.a.soudzilovskaia@cml.leidenuniv.nl>}
#+LATEX_HEADER: \affil[11]{Conservation Biology Department, Institute of Environmental Sciences, Leiden University, Leiden, The Netherlands}

#+LATEX_HEADER: \author[2]{Michael C. Dietze <dietze@bu.edu>}

#+LATEX_HEADER: \affil[*]{Corresponding author; Phone: (301) 314-6713; Fax: (301) 314-6719; Email: alexey.shiklomanov@pnnl.gov; Mail: 5825 University Research Ct., Office 3533, College Park, MD 20740}

#+LATEX_HEADER: \renewcommand\Authfont{\footnotesize}
#+LATEX_HEADER: \renewcommand\Affilfont{\scriptsize}

#+BEGIN_EXPORT latex
\begin{footnotesize}
\noindent
\textbf{Submission type:} Articles

\noindent
\textbf{Running head:} Trait covariance within vs. across PFTs (39 characters)

\noindent
\textbf{Keywords:} Functional trade-off; hierarchical modeling; trait variation; ecological modeling; leaf morphology; leaf biochemistry

\end{footnotesize}
#+END_EXPORT

#+ATTR_LATEX: :font \footnotesize
| Section               | Word count |   |         |   |
|-----------------------+------------+---+---------+---|
| Abstract              |        146 |   | Figures | 5 |
| Introduction          |        886 |   | Tables  | 1 |
| Materials and methods |       1500 |   |         |   |
| Results               |        821 |   |         |   |
| Discussion            |       1742 |   |         |   |
|-----------------------+------------+---+---------+---|
| Total                 |       5095 |   |         |   |
#+TBLFM: @4$2=1777-197-80
#+TBLFM: @7$2=vsum(@I..II)

# Subtract methods equations:
# 8 + 10 + 28 + 12 + 10 + 51 + 59 + 11 + 8 = 197
# Subtract extra counted symbols: (count-words \$\(N\|P\|R\|V\|J\)_{.*\(mass\|area\)}\$)
# >80 words

#+BEGIN_EXPORT latex
\linenumbers
\doublespacing
\pagebreak
#+END_EXPORT

* Abstract
:PROPERTIES:
:UNNUMBERED: true
:END:

The leaf economic spectrum is a widely-studied axis of plant trait variability that defines a trade-off between plant investment in leaf longevity versus productivity.
While the leaf economic spectrum has been investigated at the global scale, where it is robust, and at local scales, where deviations from it are common, it has received less attention at the intermediate scale of PFTs.
We investigated whether global leaf economic relationships are also present within plant functional types (PFTs), and the extent to which this hierarchical structure can be used to constrain trait estimates.
We developed a hierarchical multivariate Bayesian model that assumes separate means and covariance structures within and across PFTs and fit this model to seven leaf traits from the TRY database related to leaf longevity, morphology, biochemistry, and photosynthetic metabolism.
Although patterns of trait covariation were generally consistent with the leaf economic spectrum, we found three approximate tiers to this consistency:
Relationships among morphological and biochemical traits (SLA, N, P) were the most robust within and across PFTs;
relationships among metabolic traits (R_d, V_{c,max}, J_max) were slightly less so;
and relationships involving leaf lifespan was the closest to a truly hierarchical variability pattern.
Leveraging covariance in multivariate models improved trait imputation accuracy and reduced predictive uncertainties in mean trait estimates, particularly for undersampled trait-PFT combinations.

* Introduction

Plant functional traits link directly measurable features of individuals to their fitness within an ecosystem, and are often related to various aspects of whole-ecosystem function cite:violle_2007_let,cardinale_2012_impacts.
Although global trait databases are larger and more open now than ever before, large gaps and sampling biases in these databases continue to pose a challenge to trait ecology cite:cornwell_2019_what.
If all traits and plant species were completely independent from each other, the only way forward would be to collect more trait data, which is expensive and time-consuming (especially because trait data is most sparse for rare species and in places that are hardest to access, such as the tropics; cite:cornwell_2019_what).
Fortunately, this is not the case.
Recent trait syntheses have revealed that variability in plant functional traits is constrained by biophysical limitations and trade-offs between ecological strategies cite:kattge_2011_try,wright_2004_worldwide,kleyer_2015_why,diaz_2015_global.
One such constraint is the "leaf economic spectrum", which defines a trade-off between productive but short-lived leaves versus less productive but recalcitrant and long-lived leaves cite:wright_2004_worldwide,shipley_2006_fundamental,reich_2014_world,diaz_2015_global.
Leaf economic traits are correlated with
plant productivity cite:shipley_2005_functional,niinemets_2016_within,wu_2016_convergence,
litter decomposition rates cite:bakker_2010_leaf,hobbie_2015_plant,
community composition cite:burns_2004_patterns,cavender-bares_2004_multiple,
and ecosystem function cite:diaz_2004_plant,musavi_2015_imprint.
The position of species along the leaf economic spectrum is related to climate and soil conditions
cite:wright_2004_worldwide,wright_2005_modulation,cornwell_2009_community,ordonez_2009_global,wigley_2016_leaf.
As a result, relationships between leaf economic traits and climate have been used in ecosystem models to more finely resolve variation in plant function cite:sakschewski_2015_leaf,verheijen_2015_inclusion,scheiter_2013_next.

The global, interspecific trait space in which the classic leaf economic spectrum was defined is the end result of a multitude of different processes operating at different spatial, temporal, and phylogenetic scales.
The subset of these processes operating on time-scales of centuries to millennia, such as evolution or turnover in soil carbon and nutrients,
may not be relevant for predicting how individual plants and ecosystems will respond to changes on policy-relevant timescales of months to decades cite:shaw_2012_rapid.
The extent to which processes operating on these shorter timescales result in the same trait trade-offs is an open question in trait ecology.
Observational studies of trait correlations at smaller spatial scales, such as sites, species, and individuals, produce inconsistent results,
with some studies finding consistent correlations across scales cite:wright_2004_worldwide,albert_2010_multi,asner_2014_amazonian
and others finding that correlation strength and direction are scale-dependent  cite:albert_2010_intraspecific_functional_variability,messier_2010_how,wright_2012_does,feng_2013_scale,grubb_2015_relationships,wigley_2016_leaf,messier_2017_interspecific,kichenin_2013_contrasting.
Many mechanisms have been suggested for scale-dependence of trait relationships.
Trade-offs may only apply when multiple competing strategies co-occur, and alternative processes can drive community assembly where strong environmental filters severely limit the range of feasible strategies cite:rosado_2017_relative,grime_2012_evolutionary.
Different selective pressures dominate at different scales, particularly within versus across species cite:albert_2010_intraspecific_functional_variability,messier_2010_how,kichenin_2013_contrasting,
and different traits have different sensitivities to such pressures cite:messier_2016_trait.
Experimental evidence shows that species can alter different aspects of their leaf economy independently cite:wright_2012_does.
Meanwhile, global analyses show that allocation patterns (and therefore investment strategies and trait relationships) vary across plant functional types cite:ghimire_2017_global.
Moreover, plants maintain their fitness through multiple strategies, not just leaf economics, which can lead to multiple mutually orthogonal axes of trait variability.
As a result, changes in leaf economic traits often fail to predict changes in other aspects of plant function, such as
hydraulics cite:li_2015_leaf,
dispersal cite:westoby_2002_plant_ecological_strategies,
and overall plant carbon budget cite:edwards_2014_leaf.

Ascribing too much predictive power to observed global trait relationships can be problematic for all of the reasons discussed above.
On the other hand, trying to understand ecosystem through bottom-up approaches starting with individual species is also challenging.
For one, the required species-specific trait observations do not exist for a very large number of species cite:cornwell_2019_what.
Even where sufficient trait data are available, scaling functional traits to ecosystem-scale processes also requires data on species relative abundance cite:grime_1998_benefits,
which can be even more uncertain than the trait data cite:clark_2016_why.
Finally, plant interactions can result in community-level responses to environmental change that are distinct from the sum of species-specific changes cite:poorter_2003_plant.

Another strategy is to aggregate species with similar structural and functional characteristics into plant functional types (PFTs).
Although PFTs are most widely used as the unit of plant functional differentiation in dynamic vegetation and earth system models
cite:lavorel_1997_plant_functional_classifications,wullschleger_2014_plant,prentice_1992_special_paper,
the underlying concept of plant assemblages has been an important part of ecological discourse for over a century cite:cowles_1899_ecological,clements_1936_nature,naeem_2003_disentangling.
Patterns of trait variation within and across PFTs are relevant for several reasons.
First, trait covariance can be leveraged to impute missing trait values cite:swenson_2013_phylogenetic or otherwise borrowing statistical strength across different traits.
The extent to which leveraging trait covariance reduces the size (i.e. variability and/or uncertainty) of the trait space has important implications for
quantifying the parametric uncertainty in vegetation model projections cite:dietze_2013_improving,lebauer_2013_facilitating,dietze_2014_quantitative.
Second, the large uncertainty in model projections of future global carbon budgets cite:friedlingstein_2006_climate,friedlingstein_2014_uncertainties
has been at least partially attributed to the models' failure to account for plant adaptation to changing environments cite:sitch_2008_evaluation,
which has led to an increased interest in adding within-PFT trait plasticity to models cite:van_2011_going,verheijen_2015_inclusion.

While the leaf economic spectrum has been investigated at the global scale, where it is robust, and at local scales, where deviations from it are common, it has received less attention at the intermediate scale of PFTs.
Thus, this paper seeks to answer the following questions:
First, does the leaf economic spectrum hold within vs. across PFTs?
Second, can the leaf economic spectrum and similar covariance patterns be leveraged to reduce uncertainties in trait estimates, particularly under data limitation?
The answers to these question have implications for both functional ecology and ecosystem modeling.
To address these questions, we developed a hierarchical multivariate Bayesian model that explicitly accounts for across- and within-PFT variability in trait correlations.
We then fit this model to a global trait database to estimate mean trait values and variance-covariance matrices for PFTs as defined in a major earth system model (Community Land Model, CLM, citealt:clm45_note).
We evaluate the ability of this model to reduce uncertainties in trait estimates and reproduce observed patterns of global trait variation compared to univariate models.
Finally, we assess the scale dependence and generality of estimated trait covariances.

* Materials and methods

** Trait data

We focused on seven leaf traits obtained from the TRY global database cite:kattge_2011_try (see Appendix S1 in Supporting Information):
longevity (months),
specific leaf area (SLA, m$^2$ kg$^{-1}$),
nitrogen content ($N_{mass}$, mg N g$^{-1}$ or $N_{area}$, g m$^{-2}$),
phosphorus content ($P_{mass}$, mg P g$^{-1}$ or $P_{area}$, g m$^{-2}$),
dark respiration at 25°C ($R_{d,mass}$, µmol g$^{-1}$ s$^{-1}$, or $R_{d,area}$, µmol m$^{-2}$ s$^{-1}$),
maximum RuBisCO carboxylation rate at 25°C ($V_{c,max,mass}$, µmol g$^{-1}$ s$^{-1}$, or $V_{c,max,area}$, µmol m$^{-2}$ s$^{-1}$),
and maximum electron transport rate at 25°C ($J_{max,mass}$, µmol g$^{-1}$ s$^{-1}$, or $J_{max,area}$, µmol m$^{-2}$ s$^{-1}$).
For $V_{c,max}$, we only used values reported at 25°C.
For $R_{d}$ and $J_{max}$, we normalized the values to 25°C using reported leaf temperature values following Atkin /et al./ citeyear:atkin_2015_global and Kattge & Knorr citeyear:kattge_2007_temperature (equation 1 therein), respectively.
To avoid issues with trait normalization, we performed analyses separately for both mass- and area-normalized traits cite:osnas_2013_global,lloyd_2013_photosynthetically.
We restricted our analysis to quality-controlled values from species with sufficient information for functional type classification [[cite:kattge_2011_try][see]].
Following past studies [[cite:wright_2004_worldwide,onoda_2011_global,diaz_2015_global][e.g.]], we log-transformed all trait values to correct for their strong right-skewness.

** Plant functional types

We assigned each species a PFT following the scheme in the Community Land Model (CLM4.5, citealt:clm45_note) (Tab. 1, Fig. 1).
We obtained categorical data on growth form, leaf type, phenology, and photosynthetic pathway from TRY.
Where species attributes disagreed between datasets, we assigned the most frequently observed attribute (e.g., if five datasets say "shrub" but only one says "tree", we would use "shrub").
Where species attributes were missing, we assigned attributes based on higher order phylogeny if possible (e.g., /Poaceae/ family are grasses, /Larix/ genus are deciduous needleleaved trees) or omitted the species if not.
For biome specification, we matched geographic coordinates for each species to annual mean temperature ($AMT$, averaged 1970-2000) data from WorldClim-2 cite:fick_2017_worldclim,
calculated the mean AMT for all sites where each species was observed,
and then binned these species based on the following cutoffs: boreal/arctic ($AMT \leq 5^\circ C$), temperate ($AMT \leq 20^\circ C$), and tropical ($AMT > 20^\circ C$).

** Multivariate analysis

*** Basic model description

We compared three models representing different levels of complexity.
The simplest was the "univariate" model, in which each trait is independent.
For an observation $x_{i,t}$ of trait $t$ and sample $i$:

#+BEGIN_EXPORT latex
\begin{equation}
x_{i,t} \sim N(\mu_t, \sigma_t)
\end{equation}
#+END_EXPORT

where $N$ is the univariate Gaussian distribution with mean $\mu_t$ and standard deviation $\sigma_t$ for trait $t$.

The second-simplest model was the "multivariate" model, in which traits are drawn from a single multivariate distribution.
For observed trait vector ${\mathbf{x_i}}$ for sample $i$:

#+BEGIN_EXPORT latex
\begin{equation}
\mathbf{x_i} \sim mvN(\mathbf{\mu}, \mathbf{\Sigma})
\end{equation}
#+END_EXPORT

where $mvN$ is the multivariate Gaussian distribution with mean vector $\mathbf{\mu}$ and covariance matrix $\mathbf{\Sigma}$.
We fit both of these models independently for each PFT and once for the entire dataset (i.e. one global PFT).

The most complex model was the "hierarchical multivariate" model (henceforth, just "hierarchical model"),
where traits are drawn from a PFT-specific multivariate distribution describing within-PFT variation,
and whose mean vector is itself sampled from a global multivariate distribution describing variation across PFTs.
For observed trait vector $\mathbf{x}_{i,p}$ for sample $i$ belonging to PFT $p$:

#+begin_export latex
\begin{equation}
\mathbf{x}_{i,p} \sim mvN(\mathbf{\mu}_p, \mathbf{\Sigma}_p)
\end{equation}

\begin{equation}
\mathbf{\mu}_p \sim mvN(\mathbf{\mu}_g, \mathbf{\Sigma}_g)
\end{equation}
#+end_export

where $\mathbf{\mu}_p$ and $\mathbf{\Sigma}_p$ are the mean vector and covariance matrix describing variation within PFT $p$, and $\mathbf{\mu}_g$ and $\mathbf{\Sigma}_g$ are the mean vector and covariance matrix describing across-PFT (global) variation.

*** Model implementation

We fit the above models using Gibbs sampling, which leverages conjugate prior relationships for efficient exploration of the sampling space.
The main advantages of Gibbs sampling over distribution-agnostic Bayesian algorithms such as Metropolis Hastings cite:haario_2001_adaptive, Differential Evolution cite:terbraak_2008_differential, and Hamiltonian Monte-Carlo cite:neal_2011_hmc is that Gibbs sampling has a 100% proposal acceptance rate (compared to 10-65% for these algorithms), meaning that it requires roughly 2-10 times fewer MCMC iterations.

For priors on all multivariate mean vectors ($\mathbf{\mu}$), we used multivariate normal distributions.
For priors on all multivariate variance-covariance matrices, we used the Wishart distribution ($W$), which leads to the following posterior distribution:

#+BEGIN_EXPORT latex
\begin{equation}
P(\mathbf{\Sigma} \mid
  \mathbf{x}, \mathbf{\mu},
  \nu_0, \mathbf{\Sigma}_0)
\sim
  (W(\nu^*, S^*))^{-1}
\end{equation}
#+END_EXPORT

#+BEGIN_EXPORT latex
\begin{equation}
\nu^* = 1 + \nu_0 + n + m
\end{equation}
#+END_EXPORT

#+BEGIN_EXPORT latex
\begin{equation}
\mathbf{S^*} = (\mathbf{S}_0 + (\bar{\mathbf{x}} - \mu)^T (\bar{\mathbf{x}} - \mu))^{-1}
\end{equation}
#+END_EXPORT

where $n$ is the number of observations, $m$ is the number of traits in data matrix $\mathbf{x}$, and $\bar{\mathbf{x}}$ is the column means of $\mathbf{x}$.
For further details on the derivation of the conjugate relationship, see Gelman /et al./ citeyear:gelman_2003_bayesian (Section 3.6, "Multivariate normal with unknown mean and variance", pg. 72).

We used weakly-informative priors for trait means and variances (diagonals of the multivariate normal covariance matrix), the values of which are shown in Table S1.
All of the covariance (off-diagonal) terms in the prior variance matrix were set to zero.
We used uninformative priors for the Wishart distribution ($\nu_0 = 0$, $\mathbf{S}_0 = \mathrm{diag}(1, m)$).

The above equations defining the conjugacy relationship do not work if the data matrix $x$ has any missing values.
Therefore, we modeled the partially missing observations as latent variables conditioned on the present observations and estimated mean vector and covariance matrix.
This approach is conceptually similar to multiple imputation cite:white_2010_multiple,graham_2009_missing_data_analysis,
and is quite distinct from single imputation, where data are imputed once in a separate step prior to parameter estimation cite:white_2010_multiple,graham_2009_missing_data_analysis.
For a block of data $\mathbf{x\prime}$ containing missing observations in columns $\mathbf{m}$ and present observations in columns $\mathbf{p}$,
missing values $\mathbf{x\prime}[m]$ are drawn randomly from a conditional multivariate normal distribution at each iteration of the sampling algorithm:

#+BEGIN_EXPORT latex
\begin{equation}
\mathbf{x^\prime}[m|p] \sim mvN(\mathbf{\mu}^\prime, \mathbf{\Sigma}^\prime)
\end{equation}
#+END_EXPORT

#+begin_export latex
\begin{equation}
\mathbf{\mu\prime} =
  (\mathbf{x\prime}[p] - \mathbf{\mu^\prime}[p]) 
  (\mathbf{\Sigma}[p,p]^{-1} \mathbf{\Sigma}[p,m])
\end{equation}
#+end_export

#+begin_export latex
\begin{equation}
\mathbf{\Sigma\prime} = \mathbf{\Sigma}[m,m] -
  \mathbf{\Sigma}[m,p]
  (\mathbf{\Sigma}[p,p]^{-1} \mathbf{\Sigma}[p,m])
\end{equation}
#+end_export

Sampling proceeds according to the following algorithm:
Let $\mu_i$ and $\mathbf{\Sigma}_i$ be the estimates of the mean vector and covariance matrix, respectively, at MCMC iteration $i$.
Similarly, let $x_i$ be the realization of the data $\mathbf{x}\prime$ with missing (latent) values imputed at MCMC iteration $i$.

1. Initialize $\mu_1$ and $\mathbf{\Sigma}_1$ as a random draw from their respective priors.
2. Generate $x_1$ as a function of $\mu_1$ and $\mathbf{\Sigma}_1$.
3. Draw $\mu_2$ and $\mathbf{Sigma}_2$ as a function of $x_1$, according to the corresponding Gibbs sampling step.
4. Generate $x_2$ as function of $\mu_2$ and $\mathbf{\Sigma}_2$.
5. Draw $\mu_3$ and $\mathbf{Sigma}_3$ as a function of $x_2$.
6. Continue alternating these steps until a stable distribution of $\mu$ and $\mathbf{Sigma}$ is reached.

A detailed demonstration of this approach is shown in Supporting Information Method S1.
By performing imputation at every MCMC iteration, we integrate over the uncertainty in the missing data.
Combined with uninformative priors on the covariance centered on zero (as described above),
this means our approach provides an inherently conservative estimate of both trait covariances and imputed missing values.
Where data are limited, our approach will tend towards covariance estimates of zero with wide credible intervals,
and the resulting weak and uninformative covariance estimates will lead to larger uncertainties in the imputed values.

For each model fit, we ran independent five chains, continuing sampling until the final result achieved convergence as determined by a univariate Gelman-Rubin potential scale reduction statistic less than 1.1 for all parameters cite:gelman_1992_inference.
We implemented this sampling algorithm in a publicly available R cite:team_2018_r package (<http://github.com/ashiklom/mvtraits>).

** Analysis of results

To assess the consistency of within- and across-PFT trait trade-offs,
we calculated the mean and 95% credible interval of the pairwise reduced major axis slope ($M$) for each trait pair ($i$, $j$)
from posterior samples of their variance-covariance matrices ($\mathbf{\Sigma}$) using the following equation:

#+BEGIN_EXPORT latex
\begin{equation}
M_{i,j} = \frac{\mathbf{\Sigma}__{j,j}}{\mathbf{\Sigma}_{i,i}} \textmf{sign}(\mathbf{\Sigma}_{i,j})
\end{equation}
#+END_EXPORT

Although this is a Bayesian analysis and therefore has no formal tests of statistical significance,
we approximated the statistical significance of slope estimates as those whose 95% credible interval did not overlap zero.
We calculated reduced major axis slopes both within and across PFTs.

To explore patterns of trait variation across PFTs,
and to provide updated parameter values for earth system models,
we calculated the mean and 95% credible intervals of PFT-level trait estimates from our hierarchical model.
We also compare these values to to the default parameter values of CLM 4.5 (Table 8.1 in citealt:clm45_note) for SLA, $N_{mass}$, $N_{area}$, $V_{c,max,mass}$ and $V_{c,max,area}$.
To convert CLM's reported C:N ratio to $N_{mass}$, we assumed a uniform leaf C fraction of 0.46.
We then divided this calculated $N_{mass}$ by the reported SLA to obtain $N_{area}$.
We calculated $V_{c,max,mass}$ by multiplying the reported $V_{c,max,area}$ by the reported SLA.

To compare the ability of the different models to predict missing trait observations,
we performed a cross-validation where we randomly removed 1000 observations from the data
and evaluated the ability of the fitted models to impute these missing observations.
We report the results of the normalized mean root mean square error (RMSE) of these predicted observations.

To test whether multivariate and hierarchical models offer relatively more utility at smaller sample sizes,
we calculated the relative uncertainty ($\alpha$) as a function of the mean ($\mu$) and upper ($q_{0.975}$) and lower ($q_{0.025}$) confidence limits of trait estimates.

#+BEGIN_EXPORT latex
\begin{equation}
\alpha = \frac{q_{0.975} - q_{0.025}}{\mu}
\end{equation}
#+END_EXPORT

We then fit a log-linear least-squares regression relating relative uncertainty to sample size ($n$) for each model (univariate, multivariate, and hierarchical; Fig. 5).

#+BEGIN_EXPORT latex
\begin{equation}
\log{\alpha} = b_0 + b_1 \log{n}
\end{equation}
#+END_EXPORT

If all three models performed equally well at all sample sizes, their respective slope and intercept coefficients would be statistically indistinguishable.
Meanwhile, models that perform better should have
a lower intercept ($b_0$), indicating lower overall uncertainty,
and
a lower slope ($b_1$), indicating reduced sensitivity of uncertainty ($\alpha$) to sample size ($n$).

** Data and code availability

The R code and data for running these analyses is publicly available online via the Open Science Framework at https://osf.io/w8y73/.
To comply with TRY intellectual property guidelines, the trait data used in this study have been "anonymized" such that they can only be identified to the PFT level (not the species level) as required to reproduce this analysis.
The complete TRY data request used for this analysis has been archived at http://try-db.org, and can be retrieved by providing the TRY data request ID (#1584).

* Results

** Trait covariance patterns within- and across-PFTs

The direction and magnitude of pairwise trait relationships was quite variable within- and across-PFTs (Fig. 1).
Broadly, this variability can be captured by breaking up the seven leaf traits considered in this analysis into three groups:
morphology and biochemistry (SLA, N, P),
metabolism (R_d, V_{c,max}, J_max),
and leaf lifespan.

Morphological and biochemical traits (SLA, N, P) show the most robust and consistent mutual covariance of these three groups.
SLA was positively related to N_mass and P_mass, and negatively related to N_area and P_area, both across PFTs and within all PFTs.
The magnitude of the slopes between N and P (regardless of normalization), and of SLA with N_area and P_area, were relatively constant within all PFTs,
but the magnitude of the slopes of SLA with N_mass and P_mass were more variable.
In particular, temperate tree species (BlETe, BlDTe, NlETe) showed steeper SLA-N_mass slopes (more variation in SLA relative to N_mass) than most other PFTs.

Covariance among metabolic traits (R_d, V_{c,max}, J_max) was slightly less robust.
Pairwise across-PFT relationships of metabolic traits with each other were usually weaker than the corresponding within-PFT relationships, relationships of metabolic traits with morphological and biochemical traits, and relationships of morphological and biochemical traits with each other.
Within PFTs, the relationship between V_{c,max} and J_max (regardless of normalization) was largely consistent in magnitude and direction,
while the relationship of R_d with both of these traits was more variable.
Within-PFT relationships of metabolic traits with N and P were usually positive,
and relationships with SLA were usually positive under mass normalization and negative under area normalization.
Two PFTs had notable deviations from these patterns under area normalization:
Broadleaved deciduous temperate (BlDTe) trees had opposite slopes for the SLA-R_{d,area}, SLA-J_{max,area}, and N_area-R_{d,area},
while needleleaved evergreen temperate trees (NlETe) had opposite slopes for R_{d,area}-V_{c,max,area} and SLA-V_{c,max,area}.
Finally, an important feature of metabolic traits is the much larger number of near-zero pairwise slope estimates,
which is driven by the relative paucity of observations (especially pairwise observations) of these traits for many PFTs.

Slopes of all of the above traits with leaf lifespan showed the most variability.
Across-PFT relationships of leaf lifespan with other traits were, on average, stronger than across-PFT relationships among the other traits, especially for mass-normalized traits.
Within-PFT relationships of leaf lifespan with mass normalized traits were most often positive, but varied systematically with leaf habit and biome.
Namely, among deciduous PFTs, leaf lifespan-SLA and leaf lifespan-N_mass slopes were less positive or more negative in colder biomes than warmer ones
(BlETr > BlETe, BlDTr > BlDTe > BlDBo, ShDTe > ShDBo, C3GTe > C3GAr).
Meanwhile, slopes of leaf lifespan with area-normalized traits were generally weaker and idiosyncratic.

An important caveat to these results is that many slopes, including all of the across-PFT slopes, had 95% credible intervals that intersected zero.
This is primarily due to variations in the effective number of pairwise observations used to estimate the covariance matrix --
the more pairwise observations are available, the smaller the minimum covariance that can be estimated with the same level of statistical power and confidence.
For example, a power analysis of correlation coefficients (`pwr::pwr.r.test` in R; cite:r_pwr_package) showed that with 14 plant functional types ($n = 14$),
the smallest across-PFT correlation we would be able to estimate with 95% power ($\alpha = 0.95$) and confidence ($p = 0.05$) is 0.74,
so we can confidently say that all PFT correlation coefficients (different from, but closely related to slope) were smaller than that value.
That being said, because all across-PFT slopes have the same sample size,
we can reasonably expect differences in the mean strength of pairwise across-PFT trait relationships to be ecologically meaningful.
The situation is more complex for PFT-level estimates, where sample size varies by multiple orders of magnitude by PFT and trait pair (Tab.\ 1, Tab.\ S4).
In particular, high-latitude PFTs (BlDBo, NlEBo, NlD, ShDBo, and C3GAr) and metabolic traits (R_d, V_{c,max}, J_max) stand out as having particularly low sample sizes.

** Estimates of PFT-level means

Across-PFT patterns in SLA, $N_{mass}$, $P_{mass}$, and $R_{d,mass}$ were similar,
with the highest values in temperate broadleaved deciduous PFTs and the lowest values in evergreen PFTs (Fig. 2).
However, none of these patterns was universal to all four traits.
For example, tropical evergreen trees had relatively high $N_{mass}$ and average SLA and $R_{d,mass}$, but among the lowest $P_{mass}$.
Similarly, compared to grass PFTs, temperate and boreal shrubs had similar SLA but higher $N_{mass}$ and $P_{mass}$. 
Patterns were different when these traits were normalized by area instead of mass.
For example, needleleaf evergreen trees had relatively low $N_{mass}$ and $P_{mass}$ but relatively high $N_{area}$ and $P_{area}$, while the opposite was true of deciduous temperate trees and shrubs.

A key application of this study was to provide data-driven parameter estimates for Earth System models.
To this end, we compared our mean parameter estimates with corresponding default parameters in CLM 4.5 cite:clm45_note (Fig. 2).
Our SLA estimates were lower (non-overlapping 95% credible interval) than CLM parameters for all PFTs except tropical broadleaved evergreen trees.
Our $N_{mass}$ estimates showed more across-PFT variability than CLM parameters, and only agreed with CLM for evergreen temperate trees, needleleaved trees, and C3 arctic grasses.
Similarly to Kattge /et al./ citeyear:kattge_2009_quantifying, we found that CLM overestimates $V_{c,max}$, both by mass and area.

** Comparing different models

Both our multivariate and hierarchical models consistently outperformed the univariate approach in terms of their ability to impute missing trait values (Fig. 3).
The relative amount of improvement from the univariate to the multivariate or hierarchical model was roughly proportional to the sample size of the underlying trait.
For instance, for SLA---the best-sampled trait in our analysis---the hierarchical model's RMSE improved on the univariate model by only 4-6%,
while the improvement for the much more sparsely observed V_{c,max} and J_max was 30-40%.
The differences between the grouped multivariate model and the hierarchical model were negligible,
indicating that the additional information content of the across-PFT covariance is limited.

In general, leaf trait estimates from the univariate, multivariate, and hierarchical models were similar (Fig. S1).
Where estimates differed between models, the largest differences were between the univariate and multivariate models, and additional constraint from the hierarchical model relative to PFT-specific multivariate models had a minimal effect on trait estimates.
Significant differences in trait estimates between univariate and multivariate models occurred even for well-sampled traits, such as leaf nitrogen content.
We also observed differences in posterior predictive uncertainties of mean estimates with respect to sample size.
High-latitude PFTs had large uncertainties relative to other PFTs, and the traits with the largest uncertainties were dark respiration, $V_{c,max}$, and $J_{max}$.
For many of these trait-PFT combinations, the additional constraint from trait covariance provided by the multivariate and hierarchical models reduced error bars, making it possible to compare estimates against those of other PFTs.
Our analysis of the relationship between sample size and trait uncertainty found that, compared to the univariate model, the multivariate model both reduced uncertainty overall (lower intercept) and reduced the sensitivity of uncertainty to sample size (lower slope) (Fig. 4).
The hierarchical model further reduced both sensitivity to sample size and overall uncertainty, but this benefit was primarily detectable at very small sample sizes.


* Discussion

** Scale dependence of the leaf economic spectrum

The leaf economic spectrum is defined by a negative relationship between SLA and leaf lifespan, and a positive relationship of SLA with $N_{mass}$, $P_{mass}$, and photosynthesis and respiration rates cite:wright_2004_worldwide.
Our first objective was to investigate the extent to which these relationships hold within and across PFTs.
Our results suggest that, among the seven traits we investigated, there are three levels of "robustness" for leaf economic relationships.
The top tier of leaf economic relationships involves morphological and biochemical traits---SLA, N, and P---which had covariance patterns consistent with the leaf economic spectrum both across PFTs and within all PFTs.
The second tier involves metabolic traits---R_d, V_{c,max}, and J_max---which were generally consistent with the leaf economic spectrum, but with a weaker relationship across PFTs and with notable deviations within specific PFTs.
The third tier involves leaf lifespan, which had a relatively strong leaf economic spectrum signal across PFTs and within a majority of PFTs,
but which showed systematic deviations from the leaf economic spectrum within many PFTs.

The consistent direction of relationships among SLA, N, and P (by mass and area) across and within all PFTs suggests that they are driven by processes that are more-or-less universal (Fig.\ 1).
The consistent positive relationship between N and P (by mass or area) reflects the tight stoichiometric link between these two nutrients, and suggests that the variations in nutrient supply that would drive changes in the N:P ratio are larger within-PFTs than across cite:elser_2010_biological.
Meanwhile, the consistent positive relationships of SLA with mass-normalized N and P reflects the fact that increases in leaf mass per area (i.e. decreases in SLA) are driven primarily by increases in structural carbohydrates, which inevitably leads to a decline in nutrient mass fractions cite:poorter_2009_causes.
At the same time, the consistent negative relationships of SLA with area-normalized N and P reflect more recent evidence of the role of these nutrients in structural proteins cite:onoda_2017_physiological.
That being said, it should be noted that although the direction of SLA-N_mass and SLA-P_mass relationships was consistent, the magnitude of their slopes showed non-trivial variation, particularly on a mass basis.

The less robust leaf economic spectrum signal in metabolic traits (Fig.\ 1) is likely a combination of two factors:
more plasticity in plant metabolism relative to morphological and biochemical traits,
and much smaller sample sizes for confidently estimating relationships.
Plasticity in plant metabolic traits independent of the leaf economic spectrum is well documented.
For example, citeyear:kattge_2009_quantifying showed that across-PFT variation in V_{c,max,area} was driven by differences in photosynthetic N use efficiency while variation within PFTs was driven by differences in N content, and that N_area-V_{c,max,area} relationships within PFTs were variable.
More generally, there is substantial variability across PFTs in how leaf N is allocated to photosynthesis cite:ghimire_2017_global and across leaf biochemical consituents more generally cite:onoda_2011_global.
The scale dependence we observed in V_{c,max}-J_max relationship---namely, that its slope was consistent within PFTs, but very weak across PFTs---may be a reflection of strong variation in growth irradiance and temperature across biomes, which have been shown to alter the J_{max}/V_{c,max} ratio cite:hikosaka_2005_nitrogen,hikosaka_2005_temperature,xiang_2013_contrasting.
All that being said, an important limitation to these results is the relative scarcity of metabolic trait measurements, especially for high-latitude PFTs (Tab.\ 1, S4).
More pairwise observations of these metabolic traits with other leaf economic traits are needed to better understand how much these are actual ecological patterns versus just artifacts of sampling bias.

The fact that trait relationships involving leaf lifespan showed the most scale dependence and within-PFT variability (Fig.\ 1) is not particularly surprising considering that leaf habit (deciduous vs.\ evergreen)---the largest driver of global variability in leaf lifespan---is a part of the PFT definition.
As noted by citealt:wright_2004_worldwide in their original presentation of the leaf economic spectrum, specific leaf area and leaf lifespan were decoupled in deciduous species, largely because of these specues' relatively small variation in leaf lifespan.
The very inconsistent direction of relationships of area-normalized traits with leaf lifespan is also consistent with the results of citealt:wright_2004_worldwide.
The systematic differences in the leaf lifespan-SLA relationship with biome we observed among deciduous PFTs can be interpreted in terms of within-PFT climate variability.
Specifically, for deciduous species, leaf lifespan is primarily driven by the length of the local growing season, which generally decreases with annual mean temperature, whereas the larger variability in leaf lifespan of evergreen species is less sensitive (or even inversely related) to changes in climate (Fig.\ S2).
Ultimately, this suggests that leaf economic relationships related to leaf lifespan are dominated by across-PFT differences, particularly those between deciduous and evergreen PFTs, while factors driving variability in leaf lifespan within PFTs are more complex and idiosyncratic cite:reich_2014_biogeographic,wu_2016_leaf.

Across PFTs, the interaction between growth form and biome in PFT definitions (Table 1) confounds the interpretation of our observed trends in PFT means with respect to well established biogeographic patterns.
We observed as expected that arctic grasses had lower mean SLA than temperate grasses, and that evergreen trees had lower SLA than their deciduous counterparts cite:poorter_2009_causes.
However, by far our highest SLA values were for temperate deciduous broadleaf trees, rather than in grass PFTs as expected cite:poorter_2009_causes.
Similarly to Onoda /et al./ citeyear:onoda_2011_global, we found no consistent patterns in SLA with temperature:
Among broadleaved evergreen PFTs, temperate species had lower SLA than tropical, but among broadleaved deciduous PFTs, temperate species had higher SLA than both tropical and boreal species.
Unlike Reich & Oleksyn citeyear:reich_2004_global, who found that foliar N:P ratios decline with latitude, our $N_{mass}$ estimates were higher in PFTs from colder biomes compared to warmer ones while $P_{mass}$ was mostly constant between biomes.
Contrary to Atkin /et al./ citeyear:atkin_2015_global, our results for both $R_{d,mass}$ and $R_{d,area}$ failed to show a trend with respect to biome.
However, this comparison may not be entirely fair because our study design inherently averages over the extensive climatic variability within PFTs.

** Covariance as constraint

The second objective of this paper was to investigate the information content of trait covariance;
i.e. how much more can we learn about specific traits based on their relationships with other traits?
We show that accounting for covariance both improved the accuracy of trait imputation (Fig.\ 3) and reduced posterior predictive uncertainty around PFT-level trait means, particularly for undersampled trait-PFT combinations (Fig.\ 4, S1).
Moreover, accounting for covariance occasionally resulted in small but statistically significant differences in the /position/ of trait mean estimates even for well-sampled PFT-trait combinations (e.g. $N_{mass}$ for temperate broadleaved deciduous trees, Fig.\ S1).
This result echoes Diaz /et al./ citeyear:diaz_2015_global in demonstrating the importance of studying the multivariate trait space rather than individual traits. 
Such shifts suggest that sampling of these traits in TRY is not representative (Tab.\ 1; Method S2; see also citealt:kattge_2011_try).
These shifts also indicate that parameter estimates based on univariate trait data [[cite:lebauer_2013_facilitating,dietze_2014_quantitative,butler_2017_mapping][e.g.]] may not only overestimate uncertainty, but may also be systematically biased.
Although some traits in our analysis ($R_{d}$, $V_{c,max}$, and $J_{max}$) had too few observations to estimate covariance patterns for some PFTs with much statistical power,
we show that leveraging covariance increases the effective sample size of all traits.
This means that field and remote sensing studies that estimate only certain traits (like SLA and $N_{mass}$) may be able to use trait correlations to provide constraint on traits they do not directly observe (such as $P_{mass}$ and $R_{d,mass}$) cite:singh_2015_imaging,musavi_2015_imprint,lepine_2016_examining,serbin_2014_spectroscopic.
As such, future observational campaigns should consider trait covariance when deciding which traits to measure.

The additional benefit of hierarchical multivariate modeling in our study was limited, due to a combindation of the low number of points used to estimate across-PFT covariance, the weak slopes of those relationships, and the usually consistent direction of pairwise slopes within and across PFTs.
Therefore, for parameterizing the current generation of ecosystem models using well-sampled traits, simple multivariate models fit independently to each PFT may be sufficient and the additional conceptual challenges and computational overhead of hierarchical modeling are not required.
However, for modeling larger numbers of PFTs cite:boulangeat_2012_improving and especially individual species [[cite:post_1996_linkages][e.g. Linkages ---]], the benefits of hierarchical modeling may accumulate cite:dietze_2008_capturing,cressie_2009_accounting,webb_2010_structured,clark_2004_why, particularly in situations where within- and across-group covariance patterns differ.
Future work should use similar methods to explore the extent to which leaf economic relationships hold within vs. across other groups, such as taxonomic levels (species, genus, family, clade), successional stages, or spatial domains.

More generally, we foresee tremendous potential for multivariate and hierarchical modeling to elucidate the relationship between traits and organismal and ecosystem function. 
A natural next step to this study would be to apply the same approach to traits whose relationship to the leaf economic spectrum is less clear. 
One example is hydraulic traits:
While stem and leaf hydraulic traits are correlated cite:bartlett_2016_correlations, the scaling between hydraulic and leaf economic traits is poorly understood cite:reich_2014_world,li_2015_leaf. 
Similarly, reexamining the relationships defining wood cite:chave_2009_towards,fortunel_2012_leaf,baraloto_2010_decoupled and root cite:kramer-walter_2016_root,valverde-barrantes_2016_root economic spectra, as well as their relationship to the foliar traits, would provide useful information on scale-dependence of plant growth and allocation strategies.
We emphasize that the difficulty of measuring hydraulic and other non-foliar traits [[cite:jansen_2015_current][e.g.]] further increases the value of any technique that can fully leverage the information they provide.
Ultimately, multivariate and hierarchical modeling may reveal functional trade-offs that are mutually confounding at different scales, thereby enhancing our understanding of processes driving functional diversity.

** Conclusions

The vast diversity of plants is a major challenge for functional ecology and ecosystem modeling.
However, variation in plant form and function is not random, but often follows patterns driven by selective pressures.
The trait trade-offs comprising the leaf economic spectrum are one such pattern.
Our first objective in this study was to investigate the extent to which leaf economic relationships often observed at the global scale are also present within functional groups typically used in the current generation of Earth System Models.
In general, we found that relationships between leaf structure (SLA) and biochemistry (N, P) are robust within and across PFTs,
while metabolic traits (R_d, V_{c,max}, J_max) are slightly less so,
and leaf lifespan was the closest to a truly hierarchical variability pattern.
Our second objective was to evaluate the utility of using trait covariance to constrain trait estimates.
Our results indicate that accounting for covariance improves the accuracy of trait imputation, reduces posterior predictive uncertainty in trait mean estimates, and, in some cases, even significantly alters these mean estimates.
Collectively, our study highlight the importance of careful consideration of plant trait covariance across scales, both for understanding ecological processes and improving their representation in models.

* Acknowledgments
  
This project was supported by NASA grant NNX14AH65G and NSF grants 1261582, 1458021, and 1655095, as well as the TRY initiative on plant traits (http://www.try-db.org).
The TRY initiative and database is hosted, developed, and maintained by J. Kattge and G. Boenisch (Max Planck Institute for Biogeochemistry, Jena, Germany).
TRY is currently supported by DIVERSITAS/Future Earth and the German Centre for Integrative Biodiversity Research (iDiv) Halle-Jena-Leipzig.
The authors would also like to thank Ben Bond-Lamberty, Christine Rollinson, Istem Fer, and Colin Averill for their valuable feedback on early drafts of this manuscript.

* References                                                       :no_title:
  
bibliography:~/Dropbox/references/library.bib

* Tables                                                           :no_title:

#+BEGIN_EXPORT latex
\pagebreak
#+END_EXPORT

#+NAME: tab:pfts
#+BEGIN_SRC R :exports results :results output latex
library(shiklomanov2017np)
traits_file <- here::here("../np-trait-analysis/extdata/traits_analysis.rds")
try_data <- readRDS(traits_file)
n_present <- try_data %>%
  select(-ObservationID, -AccSpeciesID) %>%
  rename(pft = clm45) %>%
  group_by(pft) %>%
  summarize_all(~sum(!is.na(.x)))
n_species <- try_data %>%
  distinct(clm45, AccSpeciesID) %>%
  select(pft = clm45, species = AccSpeciesID) %>%
  count(pft, name = "Species")
n_both <- n_present %>%
  full_join(n_species, by = "pft") %>%
  mutate(
    pft = as.character(pft),
    label = pft2abbr[pft],
    pft = tools::toTitleCase(gsub("_", " ", pft)),
    pft = if_else(grepl("(Broad|Needle)", pft), paste(pft, "Tree"), pft)
  ) %>%
  select(`Label` = label, `PFT` = pft, `Species`,
         leaf_lifespan, SLA,
         ends_with("mass"), ends_with("area")) %>%
  rename(
    "Leaf lifespan" = leaf_lifespan
  )
species_caption <- paste(
  "\\label{tab:pfts}Names, labels, species counts,",
  "and number of non-missing observations of each trait",
  "for plant functional types (PFTs)",
  "used in this analysis."
)
col_names <- colnames(n_both)
col_names <- gsub("_?(mass|area)$", "", col_names)
kable(
  n_both,
  caption = species_caption,
  col.names = col_names,
  align = rep("c", ncol(n_species)),
  format = "latex",
  booktabs = TRUE
) %>%
  kableExtra::add_header_above(c(" " = 5, "Mass" = 5, "Area" = 5)) %>%
  kableExtra::kable_styling(latex_options = c("hold_position", "scale_down"))
#+END_SRC

#+RESULTS: tab:pfts
#+begin_export latex
\begin{table}[!h]

\caption{\label{tab:}\label{tab:pfts}Names, labels, species counts, and number of non-missing observations of each trait for plant functional types (PFTs) used in this analysis.}
\centering
\resizebox{\linewidth}{!}{
\begin{tabular}{ccccccccccccccc}
\toprule
\multicolumn{5}{c}{ } & \multicolumn{5}{c}{Mass} & \multicolumn{5}{c}{Area} \\
\cmidrule(l{3pt}r{3pt}){6-10} \cmidrule(l{3pt}r{3pt}){11-15}
Label & PFT & Species & Leaf lifespan & SLA & N & P & Rd & Vcmax & Jmax & N & P & Rd & Vcmax & Jmax\\
\midrule
BlETr & Broadleaf Evergreen Tropical Tree & 1229 & 153 & 11710 & 7547 & 2912 & 237 & 205 & 58 & 4023 & 1684 & 326 & 225 & 152\\
BlETe & Broadleaf Evergreen Temperate Tree & 363 & 135 & 2210 & 1811 & 1194 & 121 & 36 & 16 & 928 & 339 & 196 & 106 & 87\\
BlDTr & Broadleaf Deciduous Tropical Tree & 286 & 82 & 2166 & 1545 & 812 & 98 & 54 & 30 & 813 & 500 & 113 & 56 & 53\\
BlDTe & Broadleaf Deciduous Temperate Tree & 345 & 181 & 9536 & 5982 & 2163 & 942 & 245 & 576 & 2163 & 398 & 866 & 697 & 849\\
BlDBo & Broadleaf Deciduous Boreal Tree & 62 & 58 & 908 & 898 & 340 & 142 & 0 & 0 & 141 & 60 & 11 & 5 & 5\\
\addlinespace
NlETe & Needleleaf Evergreen Temperate Tree & 130 & 66 & 2958 & 4940 & 3729 & 262 & 92 & 91 & 1227 & 462 & 84 & 274 & 106\\
NlEBo & Needleleaf Evergreen Boreal Tree & 30 & 24 & 530 & 1457 & 393 & 493 & 0 & 0 & 101 & 14 & 16 & 3 & 3\\
NlD & Needleleaf Deciduous Tree & 19 & 16 & 195 & 328 & 179 & 34 & 1 & 0 & 48 & 10 & 3 & 4 & 0\\
ShE & Shrub Evergreen & 1120 & 298 & 5018 & 3555 & 2404 & 207 & 22 & 13 & 1376 & 747 & 205 & 41 & 32\\
ShDTe & Shrub Deciduous Temperate & 330 & 100 & 3026 & 1525 & 1227 & 10 & 9 & 1 & 576 & 281 & 13 & 33 & 19\\
\addlinespace
ShDBo & Shrub Deciduous Boreal & 94 & 80 & 482 & 552 & 313 & 0 & 1 & 1 & 133 & 51 & 0 & 1 & 1\\
C3GAr & C3 Grass Arctic & 157 & 65 & 989 & 996 & 573 & 11 & 1 & 2 & 219 & 85 & 7 & 1 & 2\\
C3GTe & C3 Grass Temperate & 624 & 76 & 6322 & 3802 & 1541 & 103 & 21 & 27 & 1257 & 382 & 93 & 52 & 47\\
C4G & C4 Grass & 255 & 31 & 1312 & 1461 & 335 & 44 & 0 & 0 & 410 & 56 & 28 & 0 & 0\\
\bottomrule
\end{tabular}}
\end{table}
#+end_export

* Figures                                                          :no_title:

#+BEGIN_EXPORT latex
\pagebreak
#+END_EXPORT

#+CAPTION: Mean pairwise reduced major axis (RMA) slope estimates calculated from within- and across-PFT covariance matrix estimates from the hierarchical model.
#+CAPTION: The slope numerator ($y$) is the outer trait and the denominator ($x$) is the inner trait (so in the top row, the slope is \Delta(leaf lifespan) / \Delta(SLA)).
#+CAPTION: Blue colors indicate positive slopes and red colors indicate negative slopes, with darker shades indicating steeper slopes.
#+CAPTION: Asterisks ("*") indicate slopes whose 95% credible intervals do not overlap zero.
#+NAME: fig:rmaslope
[[../np-trait-analysis/figures/manuscript/rma-slope-tiles.pdf]]

#+CAPTION: Mean and 95% credible interval on best estimates of traits for each plant functional type from the hierarchical model.
#+CAPTION: For leaf lifespan and SLA, results were similar whether the other traits were normalized by mass- or area-, so only results from the mass-based fit are shown.
#+CAPTION: Values and uncertainties for estimates from the hierarchical model are reported in tables S1 and S2.
#+NAME: fig:traitmeans
[[../np-trait-analysis/figures/manuscript/mean_comparison.pdf]]

#+CAPTION: Normalized mean root mean square error (RMSE) estimates from 20-fold cross-validation, by model and trait.
#+CAPTION: Normalization is such that the highest RMSE for a given trait-model combination is 1.
#+CAPTION: Model abbreviations are as follows:
#+CAPTION: `uni` is the univariate model fit separately to each PFT;
#+CAPTION: `multi` is the multivariate model fit separately to each PFT;
#+CAPTION: and `hier` is the hierarchical model.
#+NAME: fig:rmse
[[../np-trait-analysis/figures/manuscript/n-fold-rmse.pdf]]

#+CAPTION: Relative uncertainty in PFT-level trait estimates as a function of sample size for each model type.
#+CAPTION: Lines represent linear models ($\log(y) = b_0 + b_1 \log(x)$) fit independently for each model type.
#+CAPTION: In general, differences in estimate uncertainty between the univariate and multivariate models were minimal at large sample sizes but increasingly important at low sample sizes.
#+CAPTION: However, differences in estimate uncertainty between the multivariate and hierarchical models were consistently negligible.
#+NAME: fig:relativeci
[[../np-trait-analysis/figures/manuscript/relative_ci_model.pdf]]

#+BEGIN_EXPORT latex
\pagebreak
#+END_EXPORT

* COMMENT Local variables and settings
  
#+STARTUP: showall
#+STARTUP: noindent

#+BEGIN_SRC emacs-lisp :results silent
(setq org-latex-pdf-process (list "latexmk -shell-escape -bibtex -f -pdf %f"))
(setq org-latex-prefer-user-labels nil)
(setq citeproc-org-ignore-backends nil)
(setq citeproc-org-suppress-affixes-cite-link-types '("citealt"))
(setq citeproc-org-suppress-author-cite-link-types '("citeyear"))
(citeproc-org-setup)
#+END_SRC

#+BEGIN_EXPORT latex
\noindent
\textbf{Author contributions:}
ANS wrote the manuscript and implemented the analysis.
ANS and EMC designed the analysis and figures.
MCD conceived the original idea for the manuscript, guided its development, and provided financial support.
MB, SJ, KK, ÜN, and NAS provided extensive feedback on multiple drafts of the manuscript, and contributed data.
CB and YO contributed data.

\noindent
\textbf{Data accessibility:}
The R code and ancillary data for running these analyses is publicly available online via the Open Science Framework at https://osf.io/w8y73/.
The TRY data request used for this analysis has been archived at http://try-db.org,
and can be retrieved by providing the TRY data request ID (\#1584).
Alternatively, the exact pre-formatted data used in this analysis are available on request to Alexey Shiklomanov (alexey.shiklomanov@pnnl.gov).
#+END_EXPORT
