#+TITLE: Does the leaf economic spectrum hold within plant functional types? A Bayesian multivariate trait meta-analysis
#+AUTHOR:
#+DATE:

#+OPTIONS: toc:nil tags:nil
#+CSL_STYLE: ecology.csl

#+LATEX_HEADER: \usepackage[left=1in,right=1in,top=1in,bottom=1in]{geometry}
#+LATEX_HEADER: \usepackage{lineno}

#+LATEX_HEADER: \usepackage[noblocks]{authblk}

#+LATEX_HEADER: \usepackage{setspace}

#+LATEX_HEADER: \usepackage{booktabs}

#+LATEX_HEADER: \hypersetup{colorlinks=false, pdfborder={0 0 0}}

#+LATEX_HEADER: \author[1,*]{Alexey N. Shiklomanov <alexey.shiklomanov@pnnl.gov>}
#+LATEX_HEADER: \affil[1]{Joint Global Change Research Institute, Pacific Northwest National Laboratory, College Park, MD}

#+LATEX_HEADER: \author[2]{Elizabeth M. Cowdery <ecowdery@bu.edu>}
#+LATEX_HEADER: \affil[2]{Department of Earth \& Environment, Boston University, Boston, MA}

#+LATEX_HEADER: \author[3]{Michael Bahn <Michael.Bahn@uibk.ac.at>}
#+LATEX_HEADER: \affil[3]{Institute of Ecology, University of Innsbruck, 6020 Innsbruck, Austria}

#+LATEX_HEADER: \author[4]{Chaeho Byun <chaeho.byun@mail.mcgill.ca>}
#+LATEX_HEADER: \affil[4]{School of Civil and Environmental Engineering, Yonsei University, Seoul 03722, Korea}

#+LATEX_HEADER: \author[5]{Steven Jansen <steven.jansen@uni-ulm.de>}
#+LATEX_HEADER: \affil[5]{Institute of Systematic Botany and Ecology, Ulm University, Albert-Einstein-Allee 11, 89081, Ulm, Germany}

#+LATEX_HEADER: \author[6]{Koen Kramer <koen.kramer@wur.nl>}
#+LATEX_HEADER: \affil[6]{Department of Vegetation, Forest, and Landscape Ecology, Wageningen Environmental Research and Wageningen University, Wageningen, Gelderland, The Netherlands}

#+LATEX_HEADER: \author[7,8]{Vanessa Minden <vanessa.minden@uni-oldenburg.de>}
#+LATEX_HEADER: \affil[7]{Institute for Biology and Environmental Sciences, Carl von Ossietzky-University of Oldenburg, Carl von Ossietzky Str. 9-11, 26129 Oldenburg, Germany}
#+LATEX_HEADER: \affil[8]{Department of Biology, Ecology and Evolution, Vrije Universiteit Brussel, Pleinlaan 2, 1050 Brussels}

#+LATEX_HEADER: \author[9]{\"Ulo Niinemets <ylo.niinemets@emu.ee>}
#+LATEX_HEADER: \affil[9]{Institute of Agricultural and Environmental Sciences, Estonian University of Life Sciences, Kreutzwaldi 1, 51014 Tartu, Estonia}

#+LATEX_HEADER: \author[10]{Yusuke Onoda <yusuke.onoda@gmail.com>}
#+LATEX_HEADER: \affil[10]{Graduate School of Agriculture, Kyoto University, Kyoto, 605-8503, Japan}

#+LATEX_HEADER: \author[11]{Nadejda A. Soudzilovskaia <n.a.soudzilovskaia@cml.leidenuniv.nl>}
#+LATEX_HEADER: \affil[11]{Conservation Biology Department, Institute of Environmental Sciences, Leiden University, Leiden, The Netherlands}

#+LATEX_HEADER: \author[2]{Michael C. Dietze <dietze@bu.edu>}

#+LATEX_HEADER: \affil[*]{Corresponding author; Phone: (301) 314-6713; Fax: (301) 314-6719; Email: alexey.shiklomanov@pnnl.gov; Mail: 5825 University Research Ct., Office 3533, College Park, MD 20740}

#+LATEX_HEADER: \renewcommand\Authfont{\footnotesize}
#+LATEX_HEADER: \renewcommand\Affilfont{\scriptsize}

#+BEGIN_EXPORT latex
\begin{footnotesize}
\noindent
\textbf{Submission type:} Articles

\noindent
\textbf{Running head:} Trait covariance within vs. across PFTs (39 characters)

\noindent
\textbf{Keywords:} Functional trade-off; hierarchical modeling; trait variation; ecological modeling; leaf morphology; leaf biochemistry

\end{footnotesize}
#+END_EXPORT

#+ATTR_LATEX: :font \footnotesize
| Section               | Word count |   |         |   |
|-----------------------+------------+---+---------+---|
| Abstract              |        146 |   | Figures | 5 |
| Introduction          |        886 |   | Tables  | 1 |
| Materials and methods |       1500 |   |         |   |
| Results               |        821 |   |         |   |
| Discussion            |       1742 |   |         |   |
|-----------------------+------------+---+---------+---|
| Total                 |       5095 |   |         |   |
#+TBLFM: @4$2=1777-197-80
#+TBLFM: @7$2=vsum(@I..II)

# Subtract methods equations:
# 8 + 10 + 28 + 12 + 10 + 51 + 59 + 11 + 8 = 197
# Subtract extra counted symbols: (count-words \$\(N\|P\|R\|V\|J\)_{.*\(mass\|area\)}\$)
# >80 words

#+BEGIN_EXPORT latex
\linenumbers
\doublespacing
\pagebreak
#+END_EXPORT

* Abstract
  :PROPERTIES:
  :UNNUMBERED: true
  :END:
  
We investigated whether global leaf economic relationships are also present within plant functional types (PFTs), and the extent to which this hierarchical structure can be used to constrain trait estimates.
We developed a hierarchical multivariate Bayesian model that assumes separate means and covariance structures within and across PFTs and fit this model to seven leaf traits from the TRY database related to leaf morphology, biochemistry, and photosynthetic metabolism.
Trait correlations were generally consistent in direction within and across PFTs, and consistent with predictions of the leaf economic spectrum.
However, correlation strength varied substantially across PFTs indicating that leaf economic relationships within PFTs are often confounded by the unique physiology of certain plant types or environmental conditions in certain biomes.
Leveraging covariance in multivariate models reduced uncertainties in mean trait estimates, particularly for undersampled trait-PFT combinations.
The across-PFT hierarchy provided additional constraint, though this was only distinguishable at very small sample sizes.

* Introduction

Plant functional traits link directly measurable features of individuals to their fitness within an ecosystem, and are often related to various aspects of whole-ecosystem function cite:violle_2007_let.
Although global trait databases are larger and more open now than ever before, large gaps and sampling biases in these databases continue to pose a challenge to trait ecology cite:cornwell_2019_what.
If all traits and plant species were completely independent from each other, the only way forward would be to collect more trait data, which is expensive and time-consuming (especially given that trait data is most sparse for rare species and in places that are hardest to access, such as the tropics; cite:cornwell_2019_what).
Fortunately, this is not the case.
Recent trait syntheses have revealed that variability in plant functional traits is constrained by biophysical limitations and trade-offs between ecological strategies cite:kattge_2011_try,wright_2004_worldwide,kleyer_2015_why,diaz_2015_global.
One such constraint is the "leaf economic spectrum", which defines a trade-off between productive but short-lived leaves versus less productive but recalcitrant and long-lived leaves cite:wright_2004_worldwide,shipley_2006_fundamental,reich_2014_world,diaz_2015_global.
Leaf economic traits are correlated with
plant productivity cite:shipley_2005_functional,niinemets_2016_within,wu_2016_convergence,
litter decomposition rates cite:bakker_2010_leaf,hobbie_2015_plant,
community composition cite:burns_2004_patterns,cavender-bares_2004_multiple,
and ecosystem function cite:diaz_2004_plant,musavi_2015_imprint.
The position of species along the leaf economic spectrum is related to climate and soil conditions
cite:wright_2004_worldwide,wright_2005_modulation,cornwell_2009_community,ordonez_2009_global,wigley_2016_leaf.
As a result, relationships between leaf economic traits and climate have been used in ecosystem models to more finely resolve variation in plant function cite:sakschewski_2015_leaf,verheijen_2015_inclusion,scheiter_2013_next.
Meanwhile, functionally similar species into groups with common characteristics is widespread in ecological studies cite:naeem_2003_disentangling and is essential to many ecosystem models cite:lavorel_1997_plant_functional_classifications,wullschleger_2014_plant.

The use of global among-trait and trait-environment correlations, for both ecological inference and predictive modeling, has several important caveats.
First, observed global correlations may not hold at smaller scales, such as sites, species, and individuals.
Some studies suggest consistent correlations across scales cite:wright_2004_worldwide,albert_2010_multi,asner_2014_amazonian,
whereas others show no or even opposite correlations cite:albert_2010_intraspecific_functional_variability,messier_2010_how,wright_2012_does,feng_2013_scale,grubb_2015_relationships,wigley_2016_leaf,messier_2017_interspecific,kichenin_2013_contrasting.
Many mechanisms have been suggested for scale-dependence of trait relationships.
Trade-offs may only apply when multiple competing strategies co-occur, and alternative processes can drive community assembly where strong environmental filters severely limit the range of feasible strategies cite:rosado_2017_relative,grime_2012_evolutionary.
Different selective pressures dominate at different scales, particularly within versus across species cite:albert_2010_intraspecific_functional_variability,messier_2010_how,kichenin_2013_contrasting,
and different traits have different sensitivities to such pressures cite:messier_2016_trait.
Experimental evidence shows that species can alter different aspects of their leaf economy independently cite:wright_2012_does.
Meanwhile, allocation patterns (and therefore investment strategies and trait relationships) vary across plant functional types cite:ghimire_2017_global.
Second, among-trait correlations do not provide causal evidence for functional trade-offs.
Rather, these correlations set an upper limit on the dissimilarity in variation structure between traits,
such traits even moderately-correlated at one scale can still vary independently at other scales cite:messier_2016_trait.
Similarly, some trait "trade-offs" (and corresponding correlations) only occur under specific limiting conditions, in the absence of which the trait pairs are free to vary independently cite:grubb_2015_trade.
Third, plants maintain their fitness through multiple independent strategies, corresponding to multiple mutually orthogonal axes of trait variability.
For instance, changes in leaf economic traits can fail to predict changes in other aspects of plant function, such as
hydraulics cite:li_2015_leaf,
dispersal cite:westoby_2002_plant_ecological_strategies,
and overall plant carbon budget cite:edwards_2014_leaf.
Finally, the observed global trait space is the result of, among other things, thousands to millions of years of evolution and community assembly,
and may therefore be very different in shape and size from the trait space defining ecosystem responses at policy-relevant time scales of years to decades.

An alternative to using a single global set of trait trade-offs is to allow trait correlations to vary among PFTs (potentially with finer resolution, e.g. citealt:boulangeat_2012_improving)
while using statistical analyses to account for uncertainty and variability in the aggregated trait values.
For example, the Predictive Ecosystem Analyzer (PEcAn, pecanproject.org), an ecosystem model-data informatics system, parameterizes PFTs using trait probability distributions from a Bayesian meta-analysis of trait data cite:dietze_2013_improving,lebauer_2013_facilitating. 
This approach explicitly separates the processes driving PFT-level differentiation from those driving finer-scale functional variability,
and is useful for guiding future data collection and model refinement cite:dietze_2014_quantitative.
However, a univariate meta-analysis like PEcAn's fails to account for trait correlations and therefore neglects useful knowledge about relationships across PFTs and between traits.
At the other extreme, existing regional and global analyses (e.g. citealt:van_2011_going,sakschewski_2015_leaf) ignore variability within PFTs, often resulting in macroecological, evolutionary, and competitive trade-offs across PFTs being used to drive acclimation and instantaneous responses within PFTs.

While the leaf economic spectrum has been investigated at the global scale, where it is robust, and at local scales, where deviations from it are common, it has received less attention at the intermediate scale of PFTs.
Thus, this paper seeks to answer the following questions:
First, does the leaf economic spectrum hold within vs. across PFTs?
Second, can the leaf economic spectrum and similar covariance patterns be leveraged to reduce uncertainties in trait estimates, particularly under data limitation?
The answers to these question have implications for both functional ecology and ecosystem modeling.
To address these questions, we developed a hierarchical multivariate Bayesian model that explicitly accounts for across- and within-PFT variability in trait correlations.
We then fit this model to a global trait database to estimate mean trait values and variance-covariance matrices for PFTs as defined in a major earth system model (Community Land Model, CLM, citealt:clm45_note).
We evaluate the ability of this model to reduce uncertainties in trait estimates and reproduce observed patterns of global trait variation compared to univariate models.
Finally, we assess the scale dependence and generality of estimated trait covariances.

* Materials and methods

** Trait data

We focused on seven foliar traits obtained from the TRY global database cite:kattge_2011_try (see Appendix S1 in Supporting Information):
longevity (months),
specific leaf area (SLA, m$^2$ kg$^{-1}$),
nitrogen content ($N_{mass}$, mg N g$^{-1}$ or $N_{area}$, g m$^{-2}$),
phosphorus content ($P_{mass}$, mg P g$^{-1}$ or $P_{area}$, g m$^{-2}$),
dark respiration at 25°C ($R_{d,mass}$, µmol g$^{-1}$ s$^{-1}$, or $R_{d,area}$, µmol m$^{-2}$ s$^{-1}$),
maximum RuBisCO carboxylation rate at 25°C ($V_{c,max,mass}$, µmol g$^{-1}$ s$^{-1}$, or $V_{c,max,area}$, µmol m$^{-2}$ s$^{-1}$),
and maximum electron transport rate at 25°C ($J_{max,mass}$, µmol g$^{-1}$ s$^{-1}$, or $J_{max,area}$, µmol m$^{-2}$ s$^{-1}$).
For $V_{c,max}$, we only used values reported at 25°C.
For $R_{d}$ and $J_{max}$, we normalized the values to 25°C using reported leaf temperature values following Atkin /et al./ citeyear:atkin_2015_global and Kattge & Knorr citeyear:kattge_2007_temperature (equation 1 therein), respectively.
To avoid issues with trait normalization, we performed analyses separately for both mass- and area-normalized traits cite:osnas_2013_global,lloyd_2013_photosynthetically.
We restricted our analysis to quality-controlled values from species with sufficient information for functional type classification [[cite:kattge_2011_try][see]].
Following past studies [[cite:wright_2004_worldwide,onoda_2011_global,diaz_2015_global][e.g.]], we log-transformed all trait values to correct for their strong right-skewness.

** Plant functional types

We assigned each species a PFT following the scheme in the Community Land Model (CLM4.5, citealt:clm45_note) (Tab. 1, Fig. 1).
We obtained categorical data on growth form, leaf type, phenology, and photosynthetic pathway from TRY.
Where species attributes disagreed between datasets, we assigned the most frequently observed attribute (e.g., if five datasets say "shrub" but only one says "tree", we would use "shrub").
Where species attributes were missing, we assigned attributes based on higher order phylogeny if possible (e.g., /Poaceae/ family are grasses, /Larix/ genus are deciduous needleleaved trees) or omitted the species if not.
For biome specification, we matched geographic coordinates for each species to annual mean temperature ($AMT$, averaged 1970-2000) data from WorldClim-2 cite:fick_2017_worldclim,
calculated the mean AMT for all sites where each species was observed,
and then binned these species based on the following cutoffs: boreal/arctic ($AMT \leq 5^\circ C$), temperate ($AMT \leq 20^\circ C$), and tropical ($AMT > 20^\circ C$).

** Multivariate analysis

*** Basic model description

We compared three models representing different levels of complexity.
The simplest was the "univariate" model, in which each trait is independent.
For an observation $x_{i,t}$ of trait $t$ and sample $i$:

#+BEGIN_EXPORT latex
\begin{equation}
x_{i,t} \sim N(\mu_t, \sigma_t)
\end{equation}
#+END_EXPORT

where $N$ is the univariate Gaussian distribution with mean $\mu_t$ and standard deviation $\sigma_t$ for trait $t$.

The second-simplest model was the "multivariate" model, in which traits are drawn from a single multivariate distribution.
For observed trait vector ${\mathbf{x_i}}$ for sample $i$:

#+BEGIN_EXPORT latex
\begin{equation}
\mathbf{x_i} \sim mvN(\mathbf{\mu}, \mathbf{\Sigma})
\end{equation}
#+END_EXPORT

where $mvN$ is the multivariate Gaussian distribution with mean vector $\mathbf{\mu}$ and covariance matrix $\mathbf{\Sigma}$.
We fit both of these models independently for each PFT and once for the entire dataset (i.e. one global PFT).

The most complex model was the "hierarchical" model, where traits are drawn from a PFT-specific multivariate distribution describing within-PFT variation, and whose mean vector is itself sampled from a global multivariate distribution describing variation across PFTs.
For observed trait vector $\mathbf{x}_{i,p}$ for sample $i$ belonging to PFT $p$:

#+begin_export latex
\begin{equation}
\mathbf{x}_{i,p} \sim mvN(\mathbf{\mu}_p, \mathbf{\Sigma}_p)
\end{equation}

\begin{equation}
\mathbf{\mu}_p \sim mvN(\mathbf{\mu}_g, \mathbf{\Sigma}_g)
\end{equation}
#+end_export

where $\mathbf{\mu}_p$ and $\mathbf{\Sigma}_p$ are the mean vector and covariance matrix describing variation within PFT $p$, and $\mathbf{\mu}_g$ and $\mathbf{\Sigma}_g$ are the mean vector and covariance matrix describing across-PFT (global) variation.

*** Model implementation

We fit the above models using Gibbs sampling, which leverages conjugate prior relationships for efficient exploration of the sampling space.
The main advantags of Gibbs sampling over distribution-agnostic Bayesian algorithms such as Metropolis Hastings cite:haario_2001_adaptive, Differential Evolution cite:terbraak_2008_differential, and Hamiltonian Monte-Carlo cite:neal_2011_hmc is that Gibbs sampling has a 100% proposal acceptance rate (compared to 10-65% for these algorithms), meaning that it requires roughly 2-10 times fewer MCMC iterations.

For priors on all multivariate mean vectors ($\mathbf{\mu}$), we used multivariate normal distributions.
For priors on all multivariate variance-covariance matrices, we used the Wishart distribution ($W$), which leads to the following posterior distribution:

#+BEGIN_EXPORT latex
\begin{equation}
P(\mathbf{\Sigma} \mid
  \mathbf{x}, \mathbf{\mu},
  \nu_0, \mathbf{\Sigma}_0)
\sim
  (W(\nu^*, S^*))^{-1}
\end{equation}
#+END_EXPORT

#+BEGIN_EXPORT latex
\begin{equation}
\nu^* = 1 + \nu_0 + n + m
\end{equation}
#+END_EXPORT

#+BEGIN_EXPORT latex
\begin{equation}
\mathbf{S^*} = (\mathbf{S}_0 + (\mathbf{x} - \bar{\mu})^T (\mathbf{x} - \bar{\mu}))^{-1}
\end{equation}
#+END_EXPORT

where $n$ is the number of observations and $m$ is the number of traits in data matrix $x$.
For further details, see Gelman /et al./ citeyear:gelman_2003_bayesian (Section 3.6, "Multivariate normal with unknown mean and variance", pg. 72).

We modeled the partially missing observations as latent variables conditioned on the present observations and estimated mean vector and covariance matrix.
The multivariate nature of this sampling procedure makes it incapable of accommodating partially missing observations.
Therefore, our algorithm included multiple imputation of partially missing data cite:white_2010_multiple,graham_2009_missing_data_analysis.
For a block of data $\mathbf{x\prime}$ containing missing observations in columns $\mathbf{m}$ and present observations in columns $\mathbf{p}$,
missing values $\mathbf{x\prime}[m]$ are drawn randomly from a conditional multivariate normal distribution at each iteration of the sampling algorithm:

#+BEGIN_EXPORT latex
\begin{equation}
\mathbf{x^\prime}[m|p] \sim mvN(\mathbf{\mu}^\prime, \mathbf{\Sigma}^\prime)
\end{equation}
#+END_EXPORT

#+begin_export latex
\begin{equation}
\mathbf{\mu\prime} =
  (\mathbf{x\prime}[p] - \mathbf{\mu^\prime}[p]) 
  (\mathbf{\Sigma}[p,p]^{-1} \mathbf{\Sigma}[p,m])
\end{equation}
#+end_export

#+begin_export latex
\begin{equation}
\mathbf{\Sigma\prime} = \mathbf{\Sigma}[m,m] -
  \mathbf{\Sigma}[m,p]
  (\mathbf{\Sigma}[p,p]^{-1} \mathbf{\Sigma}[p,m])
\end{equation}
#+end_export

Sampling proceeds according to the following algorithm:
Let $\mu_i$ and $\mathbf{\Sigma}_i$ be the estimates of the mean vector and covariance matrix, respectively, at MCMC iteration $i$.
Similarly, let $x_i$ be the realization of the data $\mathbf{x}\prime$ with missing (latent) values imputed at MCMC iteration $i$.

1. Initialize $\mu_1$ and $\mathbf{\Sigma}_1$ as a random draw from their respective priors.
2. Generate $x_1$ as a function of $\mu_1$ and $\mathbf{\Sigma}_1$.
3. Draw $\mu_2$ and $\mathbf{Sigma}_2$ as a function of $x_1$, according to the corresponding Gibbs sampling step.
4. Generate $x_2$ as function of $\mu_2$ and $\mathbf{\Sigma}_2$.
5. Draw $\mu_3$ and $\mathbf{Sigma}_3$ as a function of $x_2$.
6. Continue alternating these steps until a stable distribution of $\mu$ and $\mathbf{Sigma}$ is reached.

A detailed demonstration of this approach is shown in Supporting Information Method S1.
By performing imputation at every MCMC iteration, we integrate over the uncertainty in the missing data.
This approach is distinct from single imputation, where data are imputed once in a separate step prior to parameter estimation cite:white_2010_multiple,graham_2009_missing_data_analysis.

For each model fit, we ran independent five chains, continuing sampling until the final result achieved convergence as determined by a univariate Gelman-Rubin potential scale reduction statistic less than 1.1 for all parameters cite:gelman_1992_inference.
We implemented this sampling algorithm in a publicly available R cite:team_2018_r package (<http://github.com/ashiklom/mvtraits>).

*** Analysis of results
    
To assess the consistency of within- and across-PFT trait trade-offs, we examined covariance estimates for each trait pair and, where the 95% credible interval of the pairwise covariance coefficient did not intersect with zero,
we calculated the eigenvalues from the variance-covariance matrix for just that trait pair and plotted the corresponding dominant eigenvectors centered on the mean estimates (Fig. 2).
This figure provides a visual representation of relative positions of PFTs in trait space and both the direction and extent of within-PFT trait covariance.
It is analogous to conceptual figures describing hierarchical trait variability across environmental gradients as presented in Cornwell & Ackerly citeyear:cornwell_2009_community and Albert /et al./ citeyear:albert_2010_intraspecific_functional_variability.

Due to the small number of points used to estimate across-PFT covariance in the hierarchical model, all of the across-PFT covariance coefficients had 95% credible intervals that overlapped zero (i.e. none were "statistically significant").
A power analysis of correlation coefficients (`pwr::pwr.r.test` in R; cite:r_pwr_package) showed that with 14 plant functional types ($n = 14$),
the smallest across-PFT correlation we would be able to estimate with 95% power ($\alpha = 0.95$) and confidence ($p = 0.05$) is 0.74,
so we can reliably say that all PFT correlation coefficients were smaller than that value.
Given the relatively low power of the across-PFT correlations, we instead compared within-PFT covariances from the hierarchical model against covariances from a single global multivariate model (henceforth referred to as "global" correlation/covariance).

Besides the consistency in the direction of trait covariance within vs. across PFTs, we also investigated the strength and predictive power of these covariances, represented by correlation coefficients (i.e. pairwise covariance normalized by each trait's variance).
We plotted the mean and 95% confidence interval of the pairwise trait correlation coefficients from the global multivariate model and PFT-specific estimates from the hierarchical model (Fig. 3).

Correlation coefficients are sensitive to data sampling, particularly sample size and range (stronger correlations when data have more samples and larger range).
To evaluate the contribution of data sampling to our correlation estimates, we plotted the each pairwise correlation coefficient squared against pairwise sample size and normalized data range (Fig. S1 and S2).

To assess multivariate and hierarchical constraint on trait estimates,
we compared the mean and 95% confidence intervals of trait estimates for each PFT from each model (Fig. 4).
For reference, we included the default parameter values of CLM 4.5 (Table 8.1 in citealt:clm45_note) for SLA, $N_{mass}$, $N_{area}$, $V_{c,max,mass}$, and $V_{c,max,area}$ in Fig. 4.
To convert CLM's reported C:N ratio to $N_{mass}$, we assumed a uniform leaf C fraction of 0.46.
We then divided this calculated $N_{mass}$ by the reported SLA to obtain $N_{area}$.
We calculated $V_{c,max,mass}$ by multiplying the reported $V_{c,max,area}$ by the reported SLA.

To test whether multivariate and hierarchical models offer relatively more utility at smaller sample sizes, we calculated the relative uncertainty ($\alpha$) as a function of the mean ($\mu$) and upper ($q_{0.975}$) and lower ($q_{0.025}$) confidence limits of trait estimates.

#+BEGIN_EXPORT latex
\begin{equation}
\alpha = \frac{q_{0.975} - q_{0.025}}{\mu}
\end{equation}
#+END_EXPORT

We then fit a log-linear least-squares regression relating relative uncertainty to sample size ($n$) for each model (univariate, multivariate, and hierarchical; Fig. 5).

#+BEGIN_EXPORT latex
\begin{equation|}
\log{\alpha} = b_0 + b_1 \log{n}
\end{equation}
#+END_EXPORT

If all three models performed equally well at all sample sizes, their respective slope and intercept coefficients would be statistically indistinguishable.
Meanwhile, models that perform better should have
a lower intercept ($b_0$), indicating lower overall uncertainty,
and
a lower slope ($b_1$), indicating reduced sensitivity of uncertainty ($\alpha$) to sample size ($n$).

** Data and code availability

The R code and data for running these analyses is publicly available online via the Open Science Framework at https://osf.io/w8y73/.
To comply with TRY intellectual property guidelines, the trait data used in this study have been "anonymized" such that they can only be identified to the PFT level (not the species level) as required to reproduce this analysis.
The complete TRY data request used for this analysis has been archived at http://try-db.org, and can be retrieved by providing the TRY data request ID (#1584).

* Results

** Trait correlation patterns across- and within-PFTs

For all traits except leaf lifespan, pairwise trait correlations were generally consistent in direction both globally and within each PFT (Fig. 2).
Mass- and area-normalized traits were all positively correlated with each other and, respectively, positively and negatively correlated with SLA, both globally and within each PFT.
Mass-based traits were generally negatively correlated with leaf lifespan, but correlations of area-based traits with leaf lifespan were more variable.
The $N_{area}$ -leaf lifespan relationship was positive globally and for evergreen shrubs, tropical broadleaved deciduous trees, temperate needleleaved evergreen trees, but negative for temperate and boreal broadleaved deciduous trees and not significant for any other PFTs.
Similarly, the correlation between $P_{area}$ and leaf lifespan was positive globally but negative for evergreen shrubs and not significant for any other PFTs.
The correlation between leaf lifespan and $R_{d,area}$ was significant and negative globally, but was not significant within any PFTs.
The only significant correlations of leaf lifespan with $V_{c,max,area}$ and $J_{max,area}$ were negative for temperate broadleaved deciduous trees.

Pairwise trait correlation strength varied depending on scale, PFT, and trait (Fig. 3).
In some cases, this variability was driven by low sample sizes (Fig. 1, S1; Tab. S3, S4).
For instance, needleleaved deciduous trees, the most undersampled PFT in our analysis, were often the only PFT for which a correlation was not statistically significant.
Similarly, we had no observations of dark respiration for deciduous boreal shrubs, which explains why we found no significant correlations of dark respiration with any other trait for that PFT.
However, the relationship between correlations strength and sample size was inconsistent (Fig. S1; Tab. S4).
Every trait pair had at least one case (and often several cases) where a better-sampled PFT showed weaker correlations than PFTs with lower sample sizes, or where correlation strength varied significantly among PFTs with similar sample sizes (Fig. S1).
Relationships between correlation strength and data range were even less consistent (Fig. S2).
Therefore, we conclude that the variation in our correlation results can not be explained by sampling alone and captures some underlying ecophysiological differences between PFTs.

** Estimates of PFT-level means

In general, leaf trait estimates from the univariate, multivariate, and hierarchical models were similar (Fig. 4, Tab. S1 and S2).
Where estimates differed between models, the largest differences were between the univariate and multivariate models, and additional constraint from the hierarchical model relative to PFT-specific multivariate models had a minimal effect on trait estimates.
Significant differences in trait estimates between univariate and multivariate models occurred even for well-sampled traits, such as leaf nitrogen content.

Across-PFT patterns in SLA and $N_{mass}$, $P_{mass}$, and $R_{d,mass}$ were similar,
with the highest values in temperate broadleaved deciduous PFTs and the lowest values in evergreen PFTs.
However, none of these patterns was universal to all four traits.
For example, tropical evergreen trees had relatively high $N_{mass}$ and average SLA and $R_{d,mass}$, but among the lowest $P_{mass}$.
Similarly, compared to grass PFTs, temperate and boreal shrubs had similar SLA but higher $N_{mass}$ and $P_{mass}$. 
Patterns were different when these traits were normalized by area instead of mass.
For example, needleleaf evergreen trees had relatively low $N_{mass}$ and $P_{mass}$ but relatively high $N_{area}$ and $P_{area}$, while the opposite was true of deciduous temperate trees and shrubs.

A key application of this study was to provide data-driven parameter estimates for Earth System Models.
To this end, we compared our mean parameter estimates with corresponding default parameters in CLM 4.5 cite:clm45_note (Fig. 4).
Our SLA estimates were significantly lower than CLM parameters for all PFTs except tropical broadleaved evergreen trees.
Our $N_{mass}$ estimates showed more across-PFT variability than CLM parameters, and only agreed with CLM for evergreen temperate trees, needleleaved trees, and C3 arctic grasses.
Similarly to Kattge /et al./ citeyear:kattge_2009_quantifying, we found that CLM overestimates $V_{c,max}$, both by mass and area. 

We observed differences in the uncertainties of mean estimates with respect to sample size.
High-latitude PFTs had large uncertainties relative to other PFTs, and the traits with the largest uncertainties were dark respiration, $V_{c,max}$, and $J_{max}$.
For many of these trait-PFT combinations, the additional constraint from trait covariance provided by the multivariate and hierarchical models reduced error bars, making it possible to compare estimates against those of other PFTs.
Our analysis of the relationship between sample size and trait uncertainty found that, compared to the univariate model, the multivariate model both reduced uncertainty overall (lower intercept) and reduced the sensitivity of uncertainty to sample size (lower slope) (Fig. 5).
The hierarchical model further reduced both sensitivity to sample size and overall uncertainty, but this benefit was primarily detectable at very small sample sizes (Fig. 5).


* Discussion

** Scale dependence of the leaf economic spectrum

The leaf economic spectrum is defined by a negative correlation between SLA and leaf lifespan, and a positive correlation of SLA with $N_{mass}$, $P_{mass}$, and photosynthesis and respiration rates cite:wright_2004_worldwide.
Our first objective was to investigate the extent to which these relationships hold within and across PFTs.
Our results indicate that the leaf economic spectrum generally holds within PFTs, at least at the functional and phylogenetic resolution of current Earth System Models.
Within PFTs, correlations between SLA, $N_{mass}$, and $P_{mass}$ were consistently positive, and correlations of these traits with leaf lifespan were generally negative (though, for many PFTs, correlations were not significantly different from zero).
Although we did not include maximum photosynthesis rate ($A_{max}$), $V_{c,max,mass}$ and $J_{max,mass}$ generally exhibited the expected positive correlations with SLA and negative correlations with leaf lifespan, as did $R_{d,mass}$, though many correlations were not significant.

While trait relationships within PFTs were consistent in direction, their strength was more variable.
For example, correlations of SLA with $N_{mass}$ and $P_{mass}$ were weaker in needleleaved PFTs compared to broadleaved PFTs.
Meanwhile, correlations of SLA with $N_{area}$ were strongly negative for all PFTs (except the data-limited needleleaved deciduous trees), and especially so in temperate needleleaved species.
Given that evergreen conifers have a relatively constant allocation of N to cell walls and RuBisCO cite:onoda_2017_physiological, our results support the idea that needleleaved species primarily adapt to their environment by changing leaf morphology (i.e. SLA) rather than foliar biochemistry cite:robakowski_2004_growth.

Correlations between leaf nutrient concentrations and traits related to photosynthetic metabolism ($V_{c,max}$ and $J_{max}$) are often used to parameterize photosynthesis in ecosystem models cite:clm45_note,rogers_2016_roadmap.
We found that the strength of these correlations was PFT-dependent.
Although trait correlations are not necessarily indicative of allocation strategies, this result supports the findings of Ghimire /et al./ citeyear:ghimire_2017_global that N allocation to photosynthesis varies widely by PFT.
In tropical evergreen broadleaved trees, for example, photosynthetic metabolism traits were better correlated with $P_{mass}$ than $N_{mass}$.
This suggests that productivity of tropical species is P-limited cite:reich_2004_global,ghimire_2017_global, that N allocation strategies are more variable under N-poor conditions cite:ghimire_2017_global, or more generally that photosynthetic metabolism is more sensitive to environmental covariates than leaf nitrogen contents cite:ali_2015_global.
Meanwhile, the relatively weak $N_{area}$ - $V_{c,max,area}$ correlation in needleleaved (compared to broadleaved) species echoes earlier results by Kattge /et al./ citeyear:kattge_2009_quantifying and suggests lower allocation of N to photosynthesis cite:ghimire_2017_global.
Considering that needleleaf-dominated boreal forests have the largest influence on global climate of any biome cite:snyder_2004_evaluating,bonan_2008_forests_climate_change, we suggest that parameterization of needleleaf tree productivity based on foliar nitrogen content in Earth System Models be treated with caution.

Correlations of all traits with leaf lifespan were weaker (and often insignificant) within most PFTs than globally.
This suggests that leaf economic relationships related to leaf lifespan are dominated by fundamental differences between deciduous and evergreen PFTs, while factors driving variability in leaf lifespan within PFTs are more complex and idiosyncratic cite:reich_2014_biogeographic,wu_2016_leaf.
However, much of this within-PFT variability is driven by variations in shade responses, and a key limitation of our study is the absence of any information about the relative canopy positions at which traits were collected cite:lusk_2008_why,keenan_2016_global.

Across PFTs, the interaction between growth form and biome in PFT definitions (Table 1) confounds the interpretation of our results with respect to well established biogeographic patterns.
We observed as expected that arctic grasses had lower mean SLA than temperate grasses, and that evergreen trees had lower SLA than their deciduous counterparts cite:poorter_2009_causes.
However, by far our highest SLA values were for temperate deciduous broadleaf trees, rather than in grass PFTs as expected cite:poorter_2009_causes.
Similarly to Onoda /et al./ citeyear:onoda_2011_global, we found no consistent patterns in SLA with temperature:
Among broadleaved evergreen PFTs, temperate species had lower SLA than tropical, but among broadleaved deciduous PFTs, temperate species had higher SLA than both tropical and boreal species.
Unlike Reich & Oleksyn citeyear:reich_2004_global, who found that foliar N:P ratios decline with latitude, our $N_{mass}$ estimates were higher in PFTs from colder biomes compared to warmer ones while $P_{mass}$ was mostly constant between biomes.
Contrary to Atkin /et al./ citeyear:atkin_2015_global, our results for both $R_{d,mass}$ and $R_{d,area}$ failed to show a trend with respect to biome.
However, this comparison may not be entirely fair because our study design inherently averages over the extensive climatic variability within PFTs.

Finally, there has been some debate about the use of mass- or area-normalized traits in analyses of the leaf economic spectrum.
Two studies cite:osnas_2013_global,lloyd_2013_photosynthetically independently concluded that leaf economic relationships among mass-based traits emerge inevitably out of variation in SLA and are therefore not ecologically meaningful.
Responses to these criticisms have suggested that both mass- and area-based normalization have merit: mass-based traits have a natural interpretation in terms of resource allocation, while area-based traits are tied to the area-based nature of energy and gas fluxes through leaf surfaces cite:westoby_2013_understanding,poorter_2013_trait_correlation_networks.
We argue that investigation of trait correlations on both a mass- and area-basis can yield biologically meaningful conclusions.
For one, our discussion of differences in ecological strategies between broadleaved and needleaved species fundamentally depends on comparative analysis of mass- and area-normalized nutrient contents.
Meanwhile, our discussion of tropical tree productivity with respect to foliar nutrient contents is supported regardless of how traits are normalized.

** Covariance as constraint

The second objective of this paper was to investigate the ability of trait covariance to reduce uncertainties in trait estimates.
We show that accounting for covariance reduced uncertainty around PFT-level trait means, particularly for undersampled trait-PFT combinations (Fig. 4 and 5).
Moreover, accounting for covariance occasionally resulted in small but statistically significant differences in the /position/ of trait mean estimates even for well-sampled PFT-trait combinations (e.g. $N_{mass}$ for temperate broadleaved deciduous trees, Fig. 4).
This result echoes Diaz /et al./ citeyear:diaz_2015_global in demonstrating the importance of studying the multivariate trait space rather than individual traits. 
Such shifts suggest that sampling of these traits in TRY is not representative (Fig. 1; see also citealt:kattge_2011_try). 
These shifts also indicate that parameter estimates based on univariate trait data [[cite:lebauer_2013_facilitating,dietze_2014_quantitative,butler_2017_mapping][e.g.]] may not only overestimate uncertainty, but may also be systematically biased.
Although some traits in our analysis ($R_{d}$, $V_{c,max}$, and $J_{max}$) still had insufficient observations necessary to reliably estimate covariance patterns for some PFTs, 
we show that leveraging covariance increases the effective sample size of all traits.
This means that field and remote sensing studies that estimate only certain traits (like SLA and $N_{mass}$)  may be able to use trait correlations to provide constraint on traits they do not directly observe (such as $P_{mass}$ and $R_{d,mass}$) cite:singh_2015_imaging,musavi_2015_imprint,lepine_2016_examining,serbin_2014_spectroscopic.
As such, future observational campaigns should consider trait covariance when deciding which traits to measure.

The additional benefit of hierarchical multivariate modeling in our study was limited, largely due to the low number of points used to estimate across-PFT covariance.
Therefore, for parameterizing the current generation of ecosystem models using well-sampled traits, simple multivariate models fit independently to each PFT may be sufficient and the additional conceptual challenges and computational overhead of hierarchical modeling are not required.
However, for modeling larger numbers of PFTs cite:boulangeat_2012_improving and especially individual species [[cite:post_1996_linkages][e.g. Linkages ---]], the benefits of hierarchical modeling may accumulate cite:dietze_2008_capturing,cressie_2009_accounting,webb_2010_structured,clark_2004_why.

More generally, we foresee tremendous potential for multivariate and hierarchical modeling to elucidate the relationship between traits and organismal and ecosystem function. 
A natural next step to this study would be to apply the same approach to traits whose relationship to the leaf economic spectrum is less clear. 
One example is hydraulic traits:
While stem and leaf hydraulic traits are correlated cite:bartlett_2016_correlations, the scaling between hydraulic and leaf economic traits is poorly understood cite:reich_2014_world,li_2015_leaf. 
Similarly, reexamining the relationships defining wood cite:chave_2009_towards,fortunel_2012_leaf,baraloto_2010_decoupled and root cite:kramer-walter_2016_root,valverde-barrantes_2016_root economic spectra, as well as their relationship to the foliar traits, would provide useful information on scale-dependence of plant growth and allocation strategies.
We emphasize that the difficulty of measuring hydraulic and other non-foliar traits [[cite:jansen_2015_current][e.g.]] further increases the value of any technique that can fully leverage the information they provide. 
Ultimately, multivariate and hierarchical modeling may reveal functional trade-offs that are mutually confounding at different scales, thereby enhancing our understanding of processes driving functional diversity.

** Conclusions

The vast diversity of plants is a major challenge for functional ecology and ecosystem modeling.
Functional diversity research fundamentally depends on dimensionality reduction through a search for meaningful pattern that can be exploited to take reasonable guesses at average behavior. 
The trait trade-offs comprising the leaf economic spectrum are one such pattern. 
Our first objective in this study was to investigate the extent to which leaf economic relationships often observed at the global scale are also present within functional groups typically used in the current generation of Earth System Models.
In general, we found that trait covariation within PFTs was generally similar to covariation observed globally, but that some within-PFT covariance patterns varied depending on trait and PFT.
Some relationships, such as the relationship between leaf N and P or between $V_{c,max}$ and $J_{max}$, varied relatively little across different PFTs and functional scales, suggesting these patterns are driven by universal constraints on leaf composition and function.
However, others, such as the relationships between foliar nutrient content (N and P) and photosynthetic metabolism ($V_{c,max}$ and $J_{max}$), are PFT-dependent and therefore more representative of biome-specific environmental constraints or long-term evolutionary processes.
Our second objective was to evaluate the utility of using trait covariance to constrain trait estimates.
Our results indicate that accounting for covariance not only reduces estimate uncertainties--especially under data limitation--but can even significantly alter estimates for well-sampled traits.  
Collectively, our study highlight the importance of careful consideration of plant trait covariance across scales, both for understanding ecological processes and improving their representation in models.

* Acknowledgments
  
This project was supported by NASA grant NNX14AH65G and NSF grants 1261582, 1458021, and 1655095, as well as the TRY initiative on plant traits (http://www.try-db.org).
The TRY initiative and database is hosted, developed, and maintained by J. Kattge and G. Boenisch (Max Planck Institute for Biogeochemistry, Jena, Germany).
TRY is currently supported by DIVERSITAS/Future Earth and the German Centre for Integrative Biodiversity Research (iDiv) Halle-Jena-Leipzig.
The authors would also like to thank Christine Rollinson, Istem Fer, and Colin Averill for their valuable feedback on early drafts of this manuscript.

* References                                                       :no_title:
  
bibliography:~/Dropbox/references/library.bib

* Tables                                                           :no_title:

#+BEGIN_EXPORT latex
\pagebreak
#+END_EXPORT

#+NAME: pfts
#+BEGIN_SRC R :exports results :results output latex
library(shiklomanov2017np)
traits_file <- here::here("../np-trait-analysis/extdata/traits_analysis.rds//")
try_data <- readRDS(traits_file)
n_present <- try_data %>%
  select(-ObservationID, -AccSpeciesID) %>%
  rename(pft = clm45) %>%
  group_by(pft) %>%
  summarize_all(~sum(!is.na(.x)))
n_species <- try_data %>%
  distinct(clm45, AccSpeciesID) %>%
  select(pft = clm45, species = AccSpeciesID) %>%
  count(pft, name = "Species")
n_both <- n_present %>%
  full_join(n_species, by = "pft") %>%
  mutate(
    pft = as.character(pft),
    label = pft2abbr[pft],
    pft = tools::toTitleCase(gsub("_", " ", pft))
  ) %>%
  select(`Label` = label, `PFT` = pft, `Species`,
         leaf_lifespan, SLA,
         ends_with("mass"), ends_with("area")) %>%
  rename(
    "Leaf lifespan" = leaf_lifespan
  )
species_caption <- paste(
  "\\label{tab:pfts}Names, labels, species counts,",
  "and number of non-missing observations of each trait",
  "for plant functional types (PFTs)",
  "used in this analysis."
)
col_names <- colnames(n_both)
col_names <- gsub("_?(mass|area)$", "", col_names)
kable(
  n_both,
  caption = species_caption,
  col.names = col_names,
  align = rep("c", ncol(n_species)),
  format = "latex",
  booktabs = TRUE
) %>%
  kableExtra::add_header_above(c(" " = 5, "Mass" = 5, "Area" = 5)) %>%
  kableExtra::kable_styling(latex_options = c("hold_position", "scale_down"))
#+END_SRC
#+RESULTS: pfts
#+begin_export latex
\begin{table}[!h]

\caption{\label{tab:}\label{tab:pfts}Names, labels, species counts, and number of non-missing observations of each trait for plant functional types (PFTs) used in this analysis.}
\centering
\resizebox{\linewidth}{!}{
\begin{tabular}{ccccccccccccccc}
\toprule
\multicolumn{5}{c}{ } & \multicolumn{5}{c}{Mass} & \multicolumn{5}{c}{Area} \\
\cmidrule(l{3pt}r{3pt}){6-10} \cmidrule(l{3pt}r{3pt}){11-15}
Label & PFT & Species & Leaf lifespan & SLA & N & P & Rd & Vcmax & Jmax & N & P & Rd & Vcmax & Jmax\\
\midrule
BlETr & Broadleaf Evergreen Tropical & 1229 & 153 & 11710 & 7547 & 2912 & 237 & 205 & 58 & 4023 & 1684 & 326 & 225 & 152\\
BlETe & Broadleaf Evergreen Temperate & 363 & 135 & 2210 & 1811 & 1194 & 121 & 36 & 16 & 928 & 339 & 196 & 106 & 87\\
BlDTr & Broadleaf Deciduous Tropical & 286 & 82 & 2166 & 1545 & 812 & 98 & 54 & 30 & 813 & 500 & 113 & 56 & 53\\
BlDTe & Broadleaf Deciduous Temperate & 345 & 181 & 9536 & 5982 & 2163 & 942 & 245 & 576 & 2163 & 398 & 866 & 697 & 849\\
BlDBo & Broadleaf Deciduous Boreal & 62 & 58 & 908 & 898 & 340 & 142 & 0 & 0 & 141 & 60 & 11 & 5 & 5\\
\addlinespace
NlETe & Needleleaf Evergreen Temperate & 130 & 66 & 2958 & 4940 & 3729 & 262 & 92 & 91 & 1227 & 462 & 84 & 274 & 106\\
NlEBo & Needleleaf Evergreen Boreal & 30 & 24 & 530 & 1457 & 393 & 493 & 0 & 0 & 101 & 14 & 16 & 3 & 3\\
NlD & Needleleaf Deciduous & 19 & 16 & 195 & 328 & 179 & 34 & 1 & 0 & 48 & 10 & 3 & 4 & 0\\
ShE & Shrub Evergreen & 1120 & 298 & 5018 & 3555 & 2404 & 207 & 22 & 13 & 1376 & 747 & 205 & 41 & 32\\
ShDTe & Shrub Deciduous Temperate & 330 & 100 & 3026 & 1525 & 1227 & 10 & 9 & 1 & 576 & 281 & 13 & 33 & 19\\
\addlinespace
ShDBo & Shrub Deciduous Boreal & 94 & 80 & 482 & 552 & 313 & 0 & 1 & 1 & 133 & 51 & 0 & 1 & 1\\
C3GAr & C3 Grass Arctic & 157 & 65 & 989 & 996 & 573 & 11 & 1 & 2 & 219 & 85 & 7 & 1 & 2\\
C3GTe & C3 Grass Temperate & 624 & 76 & 6322 & 3802 & 1541 & 103 & 21 & 27 & 1257 & 382 & 93 & 52 & 47\\
C4G & C4 Grass & 255 & 31 & 1312 & 1461 & 335 & 44 & 0 & 0 & 410 & 56 & 28 & 0 & 0\\
\bottomrule
\end{tabular}}
\end{table}
#+end_export

* Figures                                                          :no_title:

#+BEGIN_EXPORT latex
\pagebreak
#+END_EXPORT

#+CAPTION: Pairwise trait mean and covariance estimates for all data pooled globally (black) and for each PFT (colored). Covariance estimates for which credible intervals overlapped zero are indicated by x symbols at the mean estimate. $x$ and $y$ axes vary on a log scale, reflecting the fact that the model was fit using the base 10 log of all traits. With the exception of leaf lifespan, pairwise covariances are consistent in direction but vary somewhat in magnitude between PFTs, and when comparing PFT-level and global estimates. However, many pairwise covariances are not statistically significant, particularly (but not always) for undersampled traits and PFTs.
[[/Users/shik544/laptop_folders/Projects/new-phytologist-traits/np-trait-analysis/figures/manuscript/stick_pairs.pdf]]

#+CAPTION: Mean and 95% credible interval on estimates of pairwise correlation coefficients for all data pooled globally (dark grey) and for each PFT (colored). For most PFT-trait pairs, correlations are mutually consistent in magnitude but vary in strength.
[[/Users/shik544/laptop_folders/Projects/new-phytologist-traits/np-trait-analysis/figures/manuscript/correlation_boxplot.pdf]]

#+CAPTION: Mean and 95% credible interval on best estimates of traits for each plant functional type from the univariate, multivariate, and hierarchical models. For leaf lifespan and SLA, results were not significantly different between the mass- and area-based models, so only results from the mass-based model are shown. For some PFT-trait combinations, where large error bars resulting from the relatively uninformative priors are substantially larger than the variability among means, the $y$ axes are constrained to facilitate comparison. Values and uncertainties for estimates from the hierarchical model are reported in tables S1 and S2.
#+NAME: fig:traitmeans
[[/Users/shik544/laptop_folders/Projects/new-phytologist-traits/np-trait-analysis/figures/manuscript/mean_comparison.pdf]]

#+CAPTION: Relative uncertainty in PFT-level trait estimates as a function of sample size for each model type. Lines represent linear models ($\log(y) = b_0 + b_1 \log(x)$) fit independently for each model type. In general, differences in estimate uncertainty between the univariate and multivariate models were minimal at large sample sizes but increasingly important at low sample sizes. However, differences in estimate uncertainty between the multivariate and hierarchical models were consistently negligible.
[[/Users/shik544/laptop_folders/Projects/new-phytologist-traits/np-trait-analysis/figures/manuscript/relative_ci_model.pdf]]

#+BEGIN_EXPORT latex
\pagebreak
#+END_EXPORT

* COMMENT Local variables and settings
  
#+STARTUP: showall
#+STARTUP: noindent

#+BEGIN_SRC emacs-lisp :result no :eval no
(setq org-latex-pdf-process (list "latexmk -shell-escape -bibtex -f -pdf %f"))
(setq citeproc-org-ignore-backends nil)
(citeproc-org-setup)
#+END_SRC

** Old statement about A_max from Methods/Trait data:

Although maximum photosynthetic rate ($A_{max}$) was an important trait in previous studies, we omitted it for two reasons.
First, data on raw photosynthetic rates are highly sensitive to measurement methodology and environmental conditions, which were generally inconsistent or unavailable in TRY.
Second, $A_{max}$ is rarely used in vegetation models as a photosynthetic parameter because it integrates over variability in many physiologically independent traits, such as $V_{c,max}$, $J_{max}$, and stomatal conductance cite:ali_2015_global.

** Old results text on PFT-level means:
   
Evergreen PFTs, particularly temperate and boreal needleleaf trees, had the longest leaf lifespan.
Meanwhile, all deciduous PFTs had lifespans shorter than 7 months, with generally longer lifespan in warmer biomes than colder ones.

# Across-PFT patterns in SLA...

C3 grasses had the highest $V_{c,max,mass}$ and $V_{c,max,area}$.
Compared to broadleaved trees, temperate needleleaved evergreen trees had lower $V_{c,max,mass}$ but higher $V_{c,max,area}$.
Among broadleaved trees, deciduous trees had higher $V_{c,max,mass}$ and slightly higher $V_{c,max,area}$ than evergreen trees.
Between the deciduous and evergreen tree PFTs, we observed no significant trend by climate zone.

C3 grasses and temperate needleleaved evergreen trees had the highest $J_{max,area}$, but temperate broadleaved deciduous trees had the highest $J_{max,mass}$.
All of the shrub PFTs had the lowest $J_{max,mass}$ but average or above-average $J_{max,area}$, while the opposite was true of broadleaved tropical PFTs.
Of the tree PFTs, needleleaved evergreen trees had the highest $J_{max,area}$ but the lowest $J_{max,mass}$.

** Old heading blocks
   
#+BEGIN_EXPORT latex
\noindent
\textbf{Author contributions:}
ANS wrote the manuscript and implemented the analysis.
ANS and EMC designed the analysis and figures.
MCD conceived the original idea for the manuscript, guided its development, and provided financial support.
MB, SJ, KK, ÜN, and NAS provided extensive feedback on multiple drafts of the manuscript, and contributed data.
CB and YO contributed data.

\noindent
\textbf{Data accessibility:}
The R code and ancillary data for running these analyses is publicly available online via the Open Science Framework at https://osf.io/w8y73/.
The TRY data request used for this analysis has been archived at http://try-db.org,
and can be retrieved by providing the TRY data request ID (\#1584).
Alternatively, the exact pre-formatted data used in this analysis are available on request to Alexey Shiklomanov (alexey.shiklomanov@pnnl.gov).
#+END_EXPORT
